# Output a spreadsheet with a "Calendar Year Total" calculated for every year and water right


library(tidyverse)
library(openxlsx)
library(data.table)


# Use the extended water use report
# Only read in necessary columns 
# (APPLICATION_NUMBER, YEAR, AMOUNT, and DIVERSION_TYPE)
amountDF <- fread("RawData/water_use_report_extended.csv", 
                  select = c("APPLICATION_NUMBER","YEAR", "AMOUNT", "DIVERSION_TYPE"))



# Exclude reported amounts for "USE"
# Then, sum the values in "AMOUNT" separately for each APPLICATION_NUMBER and YEAR pair
# Finally, write that output to a spreadsheet
# (It uses the same filename and location as the output generated by the Expected Demand script)
# (This means that it can be used with the R Shiny App)
amountDF %>%
  filter(DIVERSION_TYPE %in% c("DIRECT", "STORAGE", "Combined (Direct + Storage)")) %>%
  group_by(APPLICATION_NUMBER, YEAR) %>%
  summarize(CALENDAR_YEAR_TOTAL = sum(AMOUNT, na.rm = TRUE)) %>%
  write.xlsx("OutputData/Calendar_Year_Totals_AF.xlsx", overwrite = TRUE)