let
    Source = Csv.Document(File.Contents("C:\Users\palemi\Water Boards\Supply and Demand Assessment - Documents\Program Watersheds\1. Watershed Folders\Test Watersheds\Test_Russian\Data\GIS_Preprocessing\RR_pods_manual_review.csv"), [Delimiter=",", Columns=54, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    Promoted_Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    Changed_Type = Table.TransformColumnTypes(Promoted_Headers, {
        {"Join_Count", Int64.Type}, {"TARGET_FID", Int64.Type}, {"APPLICATION_NUMBER", type text}, {"COUNTY", type text}, 
        {"LATITUDE", type number}, {"LONGITUDE", type number}, {"POD_ID", Int64.Type}, {"FFMTRS", type text}, 
        {"Range", type text}, {"Section", Int64.Type}, {"TownshipRange", type text}
    }),
    
    // Keep only several critical columns
    Keep_essential_columns = Table.SelectColumns(Changed_Type, {
        "APPLICATION_NUMBER", "COUNTY", "LATITUDE", "LONGITUDE", "POD_ID", "SOURCE_NAME", "WATERSHED", "FFMTRS", "MTRS", "TRIB_DESC"
    }),
    
    // Rename columns with the ewrims_prefix for consistency
    Renamed_Columns = Table.RenameColumns(Keep_essential_columns, {
        {"LATITUDE", "ewrims_latitude"}, 
        {"LONGITUDE", "ewrims_longitude"}, 
        {"SOURCE_NAME", "ewrims_SOURCE_NAME"}, 
        {"TRIB_DESC", "ewrims_TRIB_DESC"}, 
        {"WATERSHED", "ewrims_WATERSHED"},
        {"COUNTY", "ewrims_County"}
    }),
    
    // Add columns with uppercase names for Report fields
    Added_REPORT_LATITUDE = Table.AddColumn(Renamed_Columns, "REPORT_LATITUDE", each ""),
    Added_REPORT_LONGITUDE = Table.AddColumn(Added_REPORT_LATITUDE, "REPORT_LONGITUDE", each ""),
    Added_REPORT_NORTHING = Table.AddColumn(Added_REPORT_LONGITUDE, "REPORT_NORTHING", each ""),
    Added_REPORT_EASTING = Table.AddColumn(Added_REPORT_NORTHING, "REPORT_EASTING", each ""),
    Added_LAT_LON_CRS = Table.AddColumn(Added_REPORT_EASTING, "LAT_LON_CRS", each ""), // Renamed from REPORT_ZONE
    Added_REPORT_COUNTY = Table.AddColumn(Added_LAT_LON_CRS, "REPORT_COUNTY", each ""),
    Added_REPORT_SOURCE_CREEK = Table.AddColumn(Added_REPORT_COUNTY, "REPORT_SOURCE_CREEK", each ""),
    Added_REPORT_TRIBUTARY = Table.AddColumn(Added_REPORT_SOURCE_CREEK, "REPORT_TRIBUTARY", each ""),
    Added_REPORT_THENCE = Table.AddColumn(Added_REPORT_TRIBUTARY, "REPORT_THENCE", each ""),
    Added_REPORT_APN = Table.AddColumn(Added_REPORT_THENCE, "REPORT_APN", each ""),
    Added_REPORT_DATUM = Table.AddColumn(Added_REPORT_APN, "REPORT_DATUM", each ""), // Renamed from REPORT_MERIDIAN
    Added_REPORT_TOWNSHIP = Table.AddColumn(Added_REPORT_DATUM, "REPORT_TOWNSHIP", each ""),
    Added_REPORT_RANGE = Table.AddColumn(Added_REPORT_TOWNSHIP, "REPORT_RANGE", each ""),
    Added_REPORT_SECTION = Table.AddColumn(Added_REPORT_RANGE, "REPORT_SECTION", each ""),
    Added_REPORT_QSECTION = Table.AddColumn(Added_REPORT_SECTION, "REPORT_QSECTION", each ""),
    Added_REPORT_QQSECTION = Table.AddColumn(Added_REPORT_QSECTION, "REPORT_QQSECTION", each ""),
    Added_REPORT_SECTION_CORNER = Table.AddColumn(Added_REPORT_QQSECTION, "REPORT_SECTION_CORNER", each ""),
    Added_REPORT = Table.AddColumn(Added_REPORT_SECTION_CORNER, "REPORT", each ""),
    Added_NS_MOVE_FT = Table.AddColumn(Added_REPORT, "NS_MOVE_FT", each ""),
    Added_REPORT_EW_MOVE_FT = Table.AddColumn(Added_NS_MOVE_FT, "REPORT_EW_MOVE_FT", each ""),
    Added_REPORT_EW_DIRECTION = Table.AddColumn(Added_REPORT_EW_MOVE_FT, "REPORT_EW_DIRECTION", each ""),
    Added_MANUAL_OVERRIDE_KEEP_POD = Table.AddColumn(Added_REPORT_EW_DIRECTION, "MANUAL_OVERRIDE: KEEP POD", each ""), // Renamed from KEEP_POD
    Added_MANUAL_OVERRIDE_REMOVE_POD = Table.AddColumn(Added_MANUAL_OVERRIDE_KEEP_POD, "MANUAL_OVERRIDE: REMOVE POD", each ""),
    Added_MULTI_OPTIONS_CHOICE = Table.AddColumn(Added_MANUAL_OVERRIDE_REMOVE_POD, "MULTI_OPTIONS_CHOICE", each ""),
    Added_NOTES2 = Table.AddColumn(Added_MULTI_OPTIONS_CHOICE, "NOTES2", each ""), // Renamed from POD_JUSTIFICATION
    Added_STAFF = Table.AddColumn(Added_NOTES2, "STAFF", each ""),
    Added_REVIEW_DATE = Table.AddColumn(Added_STAFF, "REVIEW_DATE", each ""),
    
    // Reorder columns to ensure correct output order
    Reordered_Columns = Table.ReorderColumns(Added_REVIEW_DATE, {
        "APPLICATION_NUMBER", "POD_ID", "ewrims_latitude", "ewrims_longitude", "ewrims_County", "ewrims_SOURCE_NAME", 
        "ewrims_TRIB_DESC", "ewrims_WATERSHED", "FFMTRS", "MTRS", 
        "REPORT_LATITUDE", "REPORT_LONGITUDE", "REPORT_NORTHING", "REPORT_EASTING", "LAT_LON_CRS", 
        "REPORT_COUNTY", "REPORT_SOURCE_CREEK", "REPORT_TRIBUTARY", "REPORT_THENCE", "REPORT_APN", 
        "REPORT_DATUM", "REPORT_TOWNSHIP", "REPORT_RANGE", "REPORT_SECTION", "REPORT_QSECTION", "REPORT_QQSECTION", 
        "REPORT_SECTION_CORNER", "REPORT", "NS_MOVE_FT", "REPORT_EW_MOVE_FT", "REPORT_EW_DIRECTION", "NOTES2", "STAFF", "REVIEW_DATE", "MULTI_OPTIONS_CHOICE", "MANUAL_OVERRIDE: KEEP POD", "MANUAL_OVERRIDE: REMOVE POD"
    })
in
    Reordered_Columns