from pathlib import Path
import numpy as np
import pandas as pd
from typing import (List, Tuple, Iterator, Optional)
from datetime import (date, datetime, timedelta)
import xarray as xr
import numpy as np
import zoneinfo  # Python 3.9+
import logging
import time
from contextlib import contextmanager


@contextmanager
def time_block(
    logger: logging.Logger,
    label: str,
    *,
    level: int = logging.INFO,
    extra: Optional[dict] = None
    ) -> Iterator[None]:
    
    """
    Usage:
        with time_block(logger, "open_mfdataset", extra={"project": "X"}):
            ...
    """
    t0 = time.perf_counter()
    logger.log(level, "START %s", label, extra=extra)
    try:
        yield
    except Exception:
        # logs stack trace and preserves the exception
        logger.exception("FAIL  %s", label, extra=extra)
        raise
    finally:
        elapsed = time.perf_counter() - t0
        # You can log in milliseconds if you prefer:
        # logger.log(level, "END   %s (%.0f ms)", label, elapsed * 1000, extra=extra)
        logger.log(level, "END   %s (%.2f s)", label, elapsed, extra=extra)


class XarrayHelpers:

    def create_incremental_spatial_id_variable(self, dataset: xr.Dataset, varname: str = 'nldas_id', flip_lat: bool = False, flip_lon: bool = False) -> xr.Dataset:
        """Creates a new spatial index for the xarray dataset that is generated by counting cells row-wise. Adds the index to the dataset
            as a coordinate linked to lat and lon dimensions. Assumes dataset has a lat and lon dimension with corresponding 1-d coordinates.
        """

        # Create 1d spatial index for entire grid and save as temporary variable
        nrow = dataset["lat"].shape[0]
        ncol = dataset["lon"].shape[0]
        arr = np.arange(0,nrow*ncol,step=1)\
                .reshape(nrow,ncol)
        
        if flip_lat:
            arr = arr[-1::-1,:]
        
        if flip_lon:
            arr = arr[:,-1::-1]
        
        dataset = dataset.assign_coords(
            {varname: (('lat','lon'), arr)}
        )

        return dataset
    
    def subset_spatial_extent(self, dataset: xr.Dataset, extent: Tuple[float, float, float, float] = (25, -125, 53, -119)) -> xr.Dataset:
        """Subsets the provided nldas request dataset to the specified extent.
        
        Args:
            extent Tuple[float, float, float, float]: minimum latitude, minimum longitude, maximum latitude, maximum longitude.

        Assumptions:
            - California extent is default and should be used if no extent provided.
            - CRS is WGS84 (lat/lon)
            - dataset has lat and lon coordinates with names 'lat' and 'lon' that are 1-dimensional and monotonic.
        """
        
        if 'lat' not in dataset.coords:
            raise ValueError(f"latitude field `lat` missing from dataset.")
        
        if 'lon' not in dataset.coords:
            raise ValueError(f"longitude field `lon` missing from dataset.")
        
        if len(extent) != 4:
            raise ValueError(f"Provided extent must be in format min lat, min lon, max lat, max lon")
        
        lat_slice = slice(extent[0],extent[2])
        lon_slice = slice(extent[1], extent[3])

        return dataset.sel(lat=lat_slice, lon=lon_slice)
    

    def pad_time(self, dataset: xr.Dataset, start_datetime: datetime, end_datetime: datetime, time_scale: str = "h"):
        """Reindexes the dataset time dimension to include all hours between start and end date
        
            **WARNING**: Introduces Nan values for varaibles if times don't exist in dataset time coordinate list
        """

        # Validate the time coordinate name exists in the dataset as coordinate and dimension
        if not (("time" in dataset.coords) and ("time" in dataset.dims)):
            raise ValueError(f"Time coordinate is missing in provided xarray dataset coordinates and or dimensions")

        # Validate the requested datetime frequency
        try:
            pd.tseries.frequencies.to_offset(time_scale)
        except ValueError as e:
            raise ValueError(
                f"Invalid pandas datetime frequency '{time_scale}'. "
                "See https://pandas.pydata.org/docs/user_guide/timeseries.html#offset-aliases"
            ) from e
        
        datetime_range = pd.date_range(start=start_datetime, end=end_datetime, freq=time_scale)

        return dataset.reindex({"time": datetime_range})
    
    def extract_local_time_from_utc(self, dataset: xr.Dataset, to_tz: str = "Etc/GMT+8") -> pd.DatetimeIndex:
        """Tranforms the time coordinates by shifting their timezone from `UTC` to `to_tz`"""
        
        if not ("time" in dataset.coords ) and ("time" in dataset.dims):
            raise ValueError("Failed to convert time from UTC to local {to_tz} in target xarray dataset. Dataset missing time coordinate or dimension.")
        
        dttms = pd.DatetimeIndex(dataset.time.values)\
            .tz_localize("UTC")\
            .tz_convert(to_tz)\
            .tz_localize(None)
        
        return dttms
    
    def set_negative_to_nan(self, dataset: xr.Dataset) -> xr.Dataset:
        """
        Sets negative values to nan for all variables in dataset

        *Assumes all varaibles have numeric values
        """
        return dataset.where(dataset >= 0)

    def fill_avg_along_time(self, dataset: xr.Dataset, hourly: bool=True) -> xr.Dataset:
        """For netcdfs with hourly or daily timescale time dimensions, fills missing data for all variables in the dataset along the time dimension
            by filling with long-term average hour of year (hoy) values"""
        
        ds = dataset

        # Calculate the hour/day of year for dimensional time coordinate -> 1D dataArray
        # dataset['time'] ...
        part_of_year = ds['time'].dt.dayofyear
        if hourly:
            part_of_year = (part_of_year - 1) * 24 + ds['time'].dt.hour

        # Group Variables by hour/day of year and calculate averages -> chronological 1D array
        part_of_year = part_of_year.rename("part_of_year")
        avg = ds.groupby(part_of_year).mean("time", skipna=True)
        
        # Use hour of year DataArray to index values from the average array and assign that to New values
        # -> be sure to subtract 1 from index
        fill = avg.sel(part_of_year=part_of_year)

        return ds.where(ds.notnull(), fill)

    def fill_linear_interp_along_time(self, dataset: xr.Dataset, max_gap: pd.Timedelta = pd.Timedelta('30D')) -> xr.Dataset:
        """
        Interpolate missing values along time dimension of xr.Dataset using linear interpolation.

        Args:
            max_gap: Maximum gap size to interpolate (e.g., pd.Timedelta('30D'))
        """
        ds = dataset.interpolate_na(
            dim='time',
            method='linear',
            max_gap=max_gap
        )

        return ds
    
    def fill_nearest_along_time(self, dataset: xr.Dataset) -> xr.Dataset:
        """
        Fills nans with the nearest value along the time dimension.
        """
        return dataset.ffill(dim='time').bfill(dim='time')
    
    def nans_exist(self, da: xr.DataArray) -> bool:
        """
        Checks for nan values in the xarray data array. If nans
            exist, return True, otherwise returns False
        """
        hasnan = False
        n = np.isnan(da).sum()
        if n > 0:
            hasnan = True
        return hasnan
    
    def nans_exist_in_dataset(self, ds: xr.Dataset, exclude_vars: list = []) -> bool:
        """
        Checks all variables in xarray data set for Nan. If nans exist
            in any of the variables (excluding excluded_vars), returns
            True, otherwise, returns False.
        """
        ds_vars = [v for v in ds.data_vars if v not in exclude_vars]
        hasnan: List[bool] = []
        for var in ds_vars:
            hasnan.append(self.nans_exist(ds[var]))
        
        if any(hasnan):
            return True
        
        return False

        

class DatetimeHelpers:

    def __init__(self):
        self.tz = zoneinfo.ZoneInfo("Etc/GMT+8") # default to Pacific time

    def now(self):
        return datetime.now(self.tz)

    def month_edge(self, dttm: datetime, end: bool = False) -> datetime:
        
        month_edge = datetime(dttm.year, dttm.month, 1, 0, 0, 0, 0)
        if end:            
            if month_edge.month == 12:    
                month_edge = month_edge.replace(year=month_edge.year+1, month=1)
            else:
                month_edge = month_edge.replace(month=month_edge.month + 1)
        
            month_edge = (month_edge - timedelta(hours=1))
        
        return month_edge
    
    def datetime64_to_datetime(self, dttm: np.datetime64) -> datetime:
        """Converts numpy datetime64 into a datetime object"""
        
        ts = pd.to_datetime(dttm)
        return datetime(ts.year, ts.month, ts.day, ts.hour)



    # TODO: Update this to split by month
    def split_date_range_into_monthly_intervals(self, start_datetime: datetime, end_datetime: datetime, force_boundaries: bool = False) -> List[Tuple[datetime, datetime]]:
        """
        Splits a specified date time range into a list of monthly ranges stored as tuples.
        
            force_boundaries [bool]: Completes the months with the first day of month and last day of month regardless of inputs
        """

        # split into monthly ranges.
        
        edge_start_datetime = self.month_edge(start_datetime)
        edge_end_datetime = self.month_edge(end_datetime, end=True)
        month_starts = pd.date_range(start=edge_start_datetime, end=edge_end_datetime, freq="MS").to_pydatetime()
        month_ends = pd.date_range(start=edge_start_datetime, end=edge_end_datetime, freq="ME").to_pydatetime()\
            + timedelta(hours=23)

        intervals = np.stack([month_starts,month_ends], axis=1).tolist()
        
        if not force_boundaries:
            intervals[0][0] = start_datetime
            intervals[-1][-1] = end_datetime

        return intervals
        
    
    def naive_to_local_to_utc(self, datetime: datetime, from_tz: str = "Etc/GMT+8", tz_aware_output: bool = False):
        """Converts naive datetime to local time then to UTC and makes it timezone"""

        dttm = pd.Timestamp(datetime)

        if not dttm.tzinfo and (from_tz != "UTC"):
            dttm = dttm.tz_localize(from_tz)
        
        return dttm.tz_convert("UTC").tz_localize(None).to_pydatetime()
    
    def date_to_datetime(self, dt: date, eod: bool = False) -> datetime:
         dttm = datetime(dt.year, dt.month, dt.day)
         if eod:
             dttm = dttm.replace(hour=23)
         return dttm

class SpatialHelpers:

    def coords_from_lat_lon_arrays(self, lat: List[float], lon: List[float]) -> List[Tuple[float,float]]:
        
        if len(lat) != len(lon):
            raise ValueError(f"Number of elements in lat != lon ... can not create list of coordinate tuples.")
        
        return list(zip(lat,lon))


class StationNameHelpers:
    def clean_station_name(self, station_name: str) -> str:
        """Remove invalid characters from station name for filename."""
        bad_chars = {ord(c): "_" for c in '@/.,:'}
        return station_name.translate(bad_chars).replace(" ", "")

    def normalize_station_name(self, name: str) -> str:
        """Remove source-specific suffixes like _RAWS, _CDEC, etc."""
        suffixes = ['_RAWS', '_CDEC', '_LCD', '_NOAA']
        for suffix in suffixes:
            if name.endswith(suffix):
                return name[:-len(suffix)]
        return name

    def clean_station_id(self, station_id: str) -> str:
        return station_id.replace(":", "_")
    
class FetchCimisHelpers:

    def build_date_table(
        self,
        start: date,
        end: date
    ) -> pd.DataFrame:
        """Build a DataFrame with dates and formatted year/month/day columns."""
        dates = []
        d = start
        while d < end:
            dates.append(d.isoformat())
            d += timedelta(days=1)

        df = pd.DataFrame({"date": pd.to_datetime(dates)})
        df["year"] = df["date"].dt.year.astype(str)
        df["month"] = df["date"].dt.month.map(lambda x: f"{x:02d}")
        df["day"] = df["date"].dt.day.map(lambda x: f"{x:02d}")

        return df

    def split_date_range_into_monthly_intervals(
        self,
        start_date: date,
        end_date: date,
        force_boundaries: bool = True
    ) -> List[Tuple[date, date]]:
        """Split a date range into monthly intervals."""
        intervals = []
        current = start_date

        while current <= end_date:
            if force_boundaries:
                month_start = current.replace(day=1)

                if current.month == 12:
                    month_end = current.replace(day=31)
                else:
                    next_month = current.replace(month=current.month + 1, day=1)
                    month_end = next_month - timedelta(days=1)

                interval_start = max(month_start, start_date)
                interval_end = min(month_end, end_date)
            else:
                if current.month == 12:
                    month_end = current.replace(day=31)
                else:
                    next_month = current.replace(month=current.month + 1, day=1)
                    month_end = next_month - timedelta(days=1)

                interval_start = current
                interval_end = min(month_end, end_date)

            intervals.append((interval_start, interval_end))

            if current.month == 12:
                current = current.replace(year=current.year + 1, month=1, day=1)
            else:
                current = current.replace(month=current.month + 1, day=1)

        return intervals
