[pytest]

# Where pytest shoudl look for tests
testpaths = tests

# Add the src directory to sys.path so imports work
pythonpath = src

# Optional: show more verbose output
# addopts = -v
addopts = --basetemp=test/.pytest_tmp -q -v