# Copy the log file generated by "HLP_006_Generate_RR_Workflow_Bat.R"
# into the model hydrology output folder


#### Setup ####

# Clear the environment
base::remove(list = ls())


# Import packages
source("Scripts/HLP_000_Load_Packages.R")


# Import shared functions
source("Scripts/HLP_001_Shared_Functions_Supply.R")
source("Scripts/HLP_003_RR_Workflow_Validation_Functions.R")


#### Functions ####

mainProcedure <- function () {
  
  cat("\n\n")
  cat("Starting 'HLP_007_Archive_Log_File.R'!\n")
  
  
  # Import the start and end date
  source("Scripts/HLP_002_Validate_and_Import_Data_Scraping_Bounds.R")
  
  
  # Get the path to the hydrology folder
  dirPath <- validateHydroFolder(startDate, endDate)
  
  
  cat("[1/1]\tCopying log file...\n")
  
  
  copyFile(from = "../Workflows/RR_Workflow.log" |> 
             normalizePath(mustWork = FALSE),
           to = paste0(dirPath, "/RR_Workflow.log") |> 
             normalizePath(mustWork = FALSE))
  
  
  cat("\tDone!\n\n")
  
  
  cat(col_green("\n'HLP_007_Archive_Log_File.R' is complete!\n\n"))
  
  
  # Return nothing
  return(invisible(NULL))
  
}



#### Script Execution ####

mainProcedure()


# Clean up
base::remove(list = ls())
