# After PRMS and SRP have been run successfully, combine the outputs into 
# a single CSV that describes the raw flows available in each sub-basin
# of the Russian River watershed


# This script has several required input files:
#  (1) The "_sub_inq.csv" file generated by PRMS
#  (2) The six "_inflow_#.gag" files generated by SRP
#  (3) A CSV file containing reduction factors to apply to the GAG files' values


# These files will be combined into a single output file:
#  (1) "Raw_Flows.csv"

#### Setup ####

# Clear the environment
base::remove(list = ls())


# Import packages
source("Additional_Scripts/Load_Packages.R")


# Import shared functions
source("Shared_Scripts/!Shared_Functions_Importer.R")
source("W2_Russian_River/Scripts/HLP_003_RR_Workflow_Validation_Functions.R")


#### Functions ####

mainProcedure <- function () {
  
  cat("\n\n")
  cat("Starting 'RRW_017_Generate_Raw_Flows.R'!\n")
  
  
  # Import the start and end date
  source("W2_Russian_River/Scripts/HLP_002_Validate_and_Import_Data_Scraping_Bounds.R")
  
  
  # Locate and validate the required PRMS and SRP model files
  cat("\n[1/4]\tChecking input files...\n")
  
  
  # Check that the model hydrology folder exists
  dirPath <- validateHydroFolder(startDate, endDate)
  
  
  # From the PRMS model files, the "sub_inq.csv" output is required
  # Locate that file and confirm its existence
  inqPath <- paste0(dirPath, "/PRMS/Output") |>
    list.files(pattern = paste0("_", startDate, "_", 
                                endDate, "_sub_inq\\.csv"), 
               full.names = TRUE) |>
    sort()
  
  
  # There should only be one "sub_inq" CSV file in this folder
  # (It is an output of PRMS)
  if (length(inqPath) != 1) {
    
    # Output an error message if more than one "sub_inq" file was found
    paste0("Could Not Detect sub_inq CSV File\n\n",
           "The PRMS output files were stored in the hydrology folder (\"", 
           dirPath, "\"). There should have been exactly one CSV file that ",
           "ends with \"_sub_inq\" in the PRMS output folder. However, ",
           length(inqPath), " matches were found instead. Please investigate ",
           "the directory.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # If exactly one CSV was found, convert its path into a full absolute path
  # and validate it
  inqPath <- inqPath |>
    normalizePath(mustWork = FALSE) |>
    checkForPreviousOutput()
  
  
  # Locate the six SRP files next and confirm their existence
  gagPaths <- paste0(dirPath, "/SRP/Output/SRP_inflow_", 1:6, ".gag") |>
    normalizePath(mustWork = FALSE) |> 
    checkForPreviousOutput()
  
  
  # Get the path to the CSV containing SRP reduction factors 
  # These proportions will be applied to the values in 'gagPaths' later
  reductPath <- getFromControl_RR("GAG_FLOW_REDUCTION_FACTORS_CSV")
  
  
  # After that, read in the input files and validate them
  
  # Start with the PRMS output file
  inqDF <- getDelim(inqPath, ",", trim_ws = TRUE) |>
    validateSubCSV(inqPath, dirPath)
  
  
  # Read in the six SRP GAG files next
  gagList <- vector(mode = "list", length = length(gagPaths))
  
  
  # Iteratively read in and validate the GAG files
  for (i in 1:length(gagList)) {
    
    gagList[[i]] <- read_gag(gagPaths[i]) |>
      validateGag(gagPaths[i], dirPath)
    
  }
  
  
  # Finally, read in and validate the reduction factors
  reductionDF <- getFile(reductPath) |>
    validateReductionFactors(reductPath, length(gagList))
  
  
  cat("\tDone!\n\n")
  
  
  # The next step is to process the files and generate supply flows
  # for each sub-basin
  cat("[2/4]\tProcessing data...\n")
  
  
  # Process 'inqDF' and turn it into monthly flows (with volume units of AF)
  inqDF <- inqDF |>
    processInqCSV()
  
  
  # Do the same for the GAG files (though their procedure is more involved)
  gagDF <- gagList |>
    processGag(reductionDF)
  
  
  cat("\tDone!\n\n")
  
  
  # Combine 'inqDF' and 'gagDF' together to produce the final supply CSV file
  cat("[3/4]\tGenerating raw hydrologic flows...\n")
  
  
  # Generate 'flowDF' and validate its values
  flowDF <- mergeAndValidateFlows(inqDF, gagDF)
  
  
  # Address negative flows if detected in 'flowDF'
  adjustedDF <- adjustNegativeFlows(flowDF)
  
  
  cat("\tDone!\n\n")
  
  
  # Finally, write outputs to the model hydrology folder (and update metadata)
  cat("[4/4]\tSaving outputs...\n")
  
  
  # Store both 'adjustedDF' and 'flowDF' in the "DWRAT" "Input" folder
  flowName <- paste0(dirPath, "/DWRAT/Input/",
                     "Raw_Flows_", Sys.Date(), ".csv") |>
    normalizePath(mustWork = FALSE)
  
  
  # Save 'adjustedDF'
  adjustedDF |>
    writeOutput(flowName)
  
  
  # This version of the raw flows CSV is labeled "maybe negative"
  # because corrections for negative flows were not yet considered for it
  flowDF |>
    writeOutput(paste0(dirPath, "/DWRAT/Input/",
                       "Raw_Flows_(Maybe_Negative).csv"))
  
  
  # Archive 'reductionDF' in the model hydrology folder too
  reductionName <- paste0(dirPath, "/DWRAT/Input/SRP_Reduction_Factors.csv") |>
    normalizePath(mustWork = FALSE)
  
  
  reductionDF |>
    writeOutput(reductionName, quietly = TRUE)
  
  
  # Update the metadata CSV file to contain the names of the "Raw_Flows" and
  # original "Reduction_Factors" CSV files
  updateMetadataCSV(dirPath,
                    list("RAW_FLOWS_CSV" = flowName |>
                           str_remove("^.+[/\\\\]"),
                         "SRP_GAG_REDUCTION_FACTORS" = reductPath))
  
  
  cat("\tDone!\n\n")
  
  
  # Output a completion message
  cat(col_green("\n'RRW_017_Generate_Raw_Flows.R' is complete!\n\n"))
  
  
  # Return nothing
  return(invisible(NULL))
  
}



validateSubCSV <- function (subDF, subPath, dirPath, type = "inq", nsub = 22) {
  
  # Check either the "sub_inq" or the "sub_cfs" output file of PRMS
  
  # The two files are nearly identical
  
  # Both should contain simulated hydrological flows for the first 22 sub-basins 
  
  # The main difference is that "sub_inq" is NOT cumulative, while "sub_cfs" is
  # cumulative (i.e., upstream sub-basin flows are incorporated into downstream
  # sub-basins' values)
  
  
  # First, confirm that 'subDF' contains a "Date" column and 22 sub-basin columns
  if (length(names(subDF)) != (1 + nsub)) {
    
    paste0("Unexpected Number of Columns in sub_", type, " CSV\n\n",
           "The PRMS output file (\"", subPath, "\") should contain a \"Date\" ",
           "column and ", nsub, " additional column",
           if_else(nsub > 1, "s ", " "), "(one for each modeled sub-basin ",
           "in the Russian River watershed). Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Check for the exact column names too
  if (!all(c("Date" %in% names(subDF), 1:nsub %in% names(subDF)))) {
    
    paste0("Unexpected Columns in sub_", type, " CSV\n\n",
           "The PRMS output file (\"", subPath, "\") should contain a \"Date\" ",
           "column and ", nsub, " additional column",
           if_else(nsub > 1, "s ", " "), "(one for each modeled sub-basin ",
           "in the Russian River watershed). Each sub-basin column header ",
           "should be a number that corresponds to a modeled sub-basin",
           if_else(nsub > 1, paste0(" (\"1\" to \"", nsub, "\")"), ""), ". ",
           "Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that the sub-basin flow columns are numeric
  if (!all(map_lgl(subDF[names(subDF) != "Date"], is.numeric))) {
    
    # Identify the non-numeric columns (ignoring "Date")
    nonNumCols <- which(!map_lgl(subDF, is.numeric)) |>
      base::setdiff(which(names(subDF) == "Date"))
    
    
    # Use 'nonNumCols' in the error message
    paste0("PRMS sub_", type, " File - Column Type Issue\n\n",
           "The PRMS output file (\"", subPath, "\") should contain a \"Date\" ",
           "column and ", nsub, " additional column",
           if_else(nsub > 1, "s ", " "), "(one for each modeled sub-basin ",
           "in the Russian River watershed). Each sub-basin column should be ",
           "numeric. However, ", length(nonNumCols), " column",
           if_else(length(nonNumCols) > 1, "s ", " "), " (", 
           vec2QuotedStr(names(subDF)[nonNumCols]), ") ",
           if_else(length(nonNumCols) > 1, "are", "is"), " a different type. ",
           "Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that 'subDF' contains data from the start of PRMS to the end of 
  # the modeled water year
  
  # "metadata.csv" contains this information
  # Read in the required columns (while making sure that the fields are dates)
  metaDF <- dirPath |>
    getColsFromMetadata(c("PRMS_MODEL_START_DATE", "PRMS_MODEL_END_DATE")) |>
    mutate(PRMS_MODEL_START_DATE = as.Date(PRMS_MODEL_START_DATE, 
                                           format = "%m/%d/%Y"),
           PRMS_MODEL_END_DATE = as.Date(PRMS_MODEL_END_DATE, 
                                         format = "%m/%d/%Y"))
  
  
  # Confirm that every date between "PRMS_MODEL_START_DATE" and
  # "PRMS_MODEL_END_DATE" is present in 'subDF'
  dateSeq <- seq(from = metaDF$PRMS_MODEL_START_DATE[1],
                 to = metaDF$PRMS_MODEL_END_DATE[1],
                 by = "days")
  
  
  # This vector will contain the indices of dates that are missing
  # (It will be empty if no data is missing)
  missingDates <- which(!(dateSeq %in% subDF$Date))
  
  
  if (length(missingDates) > 0) {
    
    paste0("PRMS sub_", type, " File - Missing Data Issue\n\n",
           "The PRMS output file (\"", subPath, "\") should contain daily ",
           "flow values (in cfs). However, ", length(missingDates),
           if_else(length(missingDates) > 1, " dates are ", " date is "),
           "missing data (", vec2QuotedStr(dateSeq[missingDates]), "). ",
           "Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # As a final check, ensure no values are "NA" in 'subDF'
  if (anyNA(subDF)) {
    
    paste0("PRMS sub_", type, " File - Missing Data Issue\n\n",
           "The PRMS output file (\"", subPath, "\") should contain daily ",
           "flow values (in cfs). However, missing elements were detected in ",
           "the file. Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Return 'subDF' after that
  return(subDF)
  
}



getColsFromMetadata <- function (dirPath, colNames) {
  
  # Check "metadata.csv" for specific fields
  # Return a data frame containing only those columns
  
  
  # First, read in the metadata CSV file
  metaDF <- paste0(dirPath, "/metadata.csv") |>
    normalizePath(mustWork = FALSE) |>
    getFile(delim = ",")
  
  
  # Confirm that the desired columns are in 'metaDF'
  if (!all(colNames %in% names(metaDF))) {
    
    missingNames <- which(!(colNames %in% names(metaDF)))
    
    
    paste0("Metadata CSV File - Column",
           if_else(length(missingNames) > 1, "s", ""), 
           " Not Found\n\n",
           "The metadata file (located within \"", dirPath, "\") ",
           "is missing ", length(missingNames), " column",
           if_else(length(missingNames) > 1, "s", ""), " (", 
           vec2QuotedStr(colNames[missingNames]), ").\n\n", 
           "Please investigate and revise the scripts to address this ",
           "issue.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # If there are no issues, return only the specified columns from 'metaDF'
  return(metaDF |>
           select(all_of(colNames)))
  
}



validateGag <- function (gagDF, gagPath, dirPath) {
  
  # Check the GAG output file of SRP
  
  # It should contain simulated hydrological flows
  
  
  # First, confirm that 'gagDF' contains "Time" and "Flow" columns
  requiredCols <- c("Time", "Flow")
  
  
  # Check for the exact column names too
  if (!all(requiredCols %in% names(gagDF))) {
    
    missingColumns <- which(!(requiredCols %in% names(gagDF)))
    
    paste0("Missing Columns in SRP GAG File\n\n",
           "The SRP output file (\"", gagPath, "\") should have several ",
           "specific columns (", vec2QuotedStr(requiredCols), "). However, ",
           "this is not the case (missing ", 
           vec2QuotedStr(requiredCols[missingColumns]), 
           "). Please investigate the file (", vec2QuotedStr(gagPath), 
           ") and `read_gag`.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that the "Time" and "Flow" columns are numeric
  if (!all(map_lgl(gagDF[requiredCols], is.numeric))) {
    
    # Identify the non-numeric columns
    nonNumCols <- which(!map_lgl(gagDF[requiredCols], is.numeric))
    
    
    # Use 'nonNumCols' in the error message
    paste0("SRP GAG File - Column Type Issue\n\n",
           "The SRP output file (\"", gagPath, "\") should have several ",
           "specific columns (", vec2QuotedStr(requiredCols), "). These ",
           "columns should all have numeric values. However, that is not the ",
           "case for all columns (", 
           vec2QuotedStr(requiredCols[nonNumCols]), 
           "). Please investigate the file (", vec2QuotedStr(gagPath), 
           ") and `read_gag`.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that 'gagDF' contains data from the start of the SRP run to the end 
  # of the modeled water year
  
  # "metadata.csv" contains this information
  # Read in the required columns (while making sure that the fields are dates)
  metaDF <- dirPath |>
    getColsFromMetadata(c("SRP_MODEL_START_DATE", "SRP_MODEL_END_DATE")) |>
    mutate(SRP_MODEL_START_DATE = as.Date(SRP_MODEL_START_DATE, 
                                           format = "%m/%d/%Y"),
           SRP_MODEL_END_DATE = as.Date(SRP_MODEL_END_DATE, 
                                         format = "%m/%d/%Y"))
  
  
  # Confirm that every date between "SRP_MODEL_START_DATE" and
  # "SRP_MODEL_END_DATE" is present in 'inqDF'
  dateSeq <- seq(from = metaDF$SRP_MODEL_START_DATE[1],
                 to = metaDF$SRP_MODEL_END_DATE[1],
                 by = "days")
  
  
  # The main issue is that 'gagDF' does not have a date column
  # "Time" is just a count from the start date
  
  # Verify then that the length of 'dateSeq' equals the number of
  # rows in 'gagDF'
  if (length(dateSeq) != nrow(gagDF)) {
    
    paste0("SRP Gag File - Missing Data Issue\n\n",
           "The SRP GAG files should contain daily flow values (in cfs). ",
           "However, this file contains ", nrow(gagDF), " records when ",
           length(dateSeq), " are expected. Please investigate the file (",
           vec2QuotedStr(gagPath), ").") |>
      errWrap() |>
      stop()
    
  }
  
  
  # If there are no missing dates, add 'dateSeq' to 'gagDF'
  # (This will be easier to work with than "Time")
  gagDF <- gagDF |>
    arrange(Time) |>
    mutate(DATE = dateSeq)
  
  
  # As a final check, ensure no values are "NA" in 'gagDF'
  if (anyNA(gagDF)) {
    
    paste0("SRP Gag File - Missing Data Issue\n\n",
           "The SRP GAG files should contain daily flow values (in cfs). ",
           "However, this file contains missing elements where values are ",
           "expected. Please investigate the file (",
           vec2QuotedStr(gagPath), ") and `read_gag`.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Return 'gagDF' after that
  return(gagDF)
  
}



validateReductionFactors <- function (reductionDF, reductPath, numGag) {
  
  # This CSV file should contain decimal proportions to apply to 
  # the flow values in each of the GAG files
  
  # Check that all required columns are present
  # Sensible values should be input as well
  
  
  # First, confirm that 'reductionDF' contains a "Month" column 
  # It should also have a separate numeric column for each GAG file
  if (length(names(reductionDF)) != (1 + numGag)) {
    
    paste0("Unexpected Number of Columns in SRP Reduction Factors CSV\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column and ", numGag, " additional column",
           if_else(numGag > 1, "s ", " "), "(one for each GAG file output by ",
           "SRP). Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Check for the exact column names too
  if (!all(c("Month" %in% names(reductionDF), 
                 1:numGag %in% names(reductionDF)))) {
    
    paste0("Unexpected Columns in SRP Reduction Factors CSV\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column and ", numGag, " additional column",
           if_else(numGag > 1, "s ", " "), "(one for each GAG file output by ",
           "SRP). Each GAG file's column header should be a number that ",
           "corresponds to that file's index number ",
           if_else(numGag > 1, paste0(" (\"1\" to \"", numGag, "\")"), ""), 
           ". Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that all columns are numeric
  if (!all(map_lgl(reductionDF, is.numeric))) {
    
    # Identify the non-numeric columns
    nonNumCols <- which(!map_lgl(reductionDF, is.numeric))
    
    
    # Use 'nonNumCols' in the error message
    paste0("SRP Reduction Factors CSV File - Column Type Issue\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column and ", numGag, " additional column",
           if_else(numGag > 1, "s ", " "), "(one for each GAG file output by ",
           "SRP). Every column should be numeric. However, ", length(nonNumCols),
           " column", if_else(length(nonNumCols) > 1, "s ", " "), " (", 
           vec2QuotedStr(names(reductionDF)[nonNumCols]), ") ",
           if_else(length(nonNumCols) > 1, "are", "is"), " a different type. ",
           "Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that "Month" has a value for all months of the year
  if (!all(1:12 %in% reductionDF$Month) || nrow(reductionDF) != 12) {
    
    paste0("SRP Reduction Factors CSV File - Incomplete Data Issue\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column with one row per month. However, this ",
           "is not the case. Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Check for "NA" values after that
  if (anyNA(reductionDF)) {
    
    paste0("SRP Reduction Factors CSV File - Missing Data Issue\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column and ", numGag, "columns that correspond ",
           "to each SRP GAG file. There should be one row per month, and a ",
           "reduction factor for each GAG file. However, one or more missing ",
           "elements were detected in the file. Please investigate it.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # The reduction factors should primarily be less than 1
  # Output a warning if any reduction factor is greater than 1
  if (max(reductionDF[names(reductionDF) != "Month"]) > 1) {
    
    paste0("Warning! Unusual Factor Detected!\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain factors that reduce the flow values in GAG files (e.g., ",
           "0.90 for a 10% reduction). However, at least one proportion is ",
           "greater than one. Was that intentional?") |>
      errWrap() |>
      message()
    
  }
  
  
  # Return 'reductionDF' after that
  return(reductionDF)
  
}



processInqCSV <- function (inqDF) {
  
  # The PRMS sub_inq file contains daily flows in cubic feet per second (cfs)
  
  # This data will be wrapped up into monthly flows 
  # The new units will be acre-feet per month (AF/month)
  
  
  # First, convert "cfs" into acre-feet per day:
  
  #  (*) There are 43,559.9 ft^3 in 1 AF
  #  (*) There are 60 * 60 * 24 seconds in 1 day
  
  # ft^3/s * 60 s/min * 60 min/hr * 24 hr/day * 1/43559.9 AF/ft^3
  inqDF <- inqDF |>
    mutate(across(matches("[0-9]"), ~ . * 60 * 60 * 24 / 43559.9))
  
  
  # After that, sum up the AF/day values by year and month
  inqDF <- inqDF |>
    mutate(YEAR = year(Date),
           MONTH = month(Date)) |>
    group_by(YEAR, MONTH) |>
    summarize(across(matches("[0-9]"), sum), .groups = "drop")
  
  
  # Return 'inqDF' afterwards
  return(inqDF)
  
}



processGag <- function (gagList, reductionDF) {
  
  # The six SRP GAG files contain daily flows in cubic feet per second (cfs)*
  
  # This data will be consolidated into monthly flows for six sub-basins in the
  # Russian River watershed
  # The new units will be acre-feet per month (AF/month)
  
  # * = Although the units are stated to be cfs, they are wrapped up into daily 
  # values already, meaning that ft^3/day is the actual starting point for 
  # unit conversions
  
  
  # From each GAG file, extract the "DATE" and "Flow" columns
  # Rename "Flow" and then combine these GAG files together
  for (i in 1:length(gagList)) {
    
    tempDF <- gagList[[i]] |>
      select(DATE, Flow) |>
      rename(!! paste0("GAG_", i) := Flow)
    
    
    # Consolidate 'tempDF' from each of the GAG files
    if (i == 1) {
      
      gagDF <- tempDF
      
    } else {
      
      gagDF <- full_join(gagDF, tempDF, by = "DATE", 
                         relationship = "one-to-one")
      
    }
    
  }
  
  
  # Use "DATE" to calculate a "YEAR" and "Month" column 
  # After that, append 'reductionDF' using "Month"
  gagDF <- gagDF |>
    mutate(YEAR = year(DATE), Month = month(DATE)) |>
    left_join(reductionDF, by = "Month", relationship = "many-to-one")
  
  
  # Apply the reduction factors to the daily CFS values
  gagDF[paste0("GAG_", 1:length(gagList))] <- 
    gagDF[paste0("GAG_", 1:length(gagList))] * gagDF[as.character(1:length(gagList))]
  
  
  # Keep only the datetime columns and "GAG" columns before proceeding
  # (Rename "Month" into "MONTH" too)
  gagDF <- gagDF |>
    select(DATE, YEAR, Month, starts_with("GAG_")) |>
    rename(MONTH = Month)
  
  
  # Convert the units from ft^3/day to AF/day next
  # (There are 43,559.9 cubic feet in 1 acre-foot)
  gagDF <- gagDF |>
    mutate(across(starts_with("GAG_"), ~ . / 43559.9))
  
  
  # After that, define the sub-basin flow values using the GAG data
  gagDF <- gagDF |>
    mutate(`23` = GAG_1,
           `24` = GAG_6 - GAG_1 - GAG_5,
           `25` = GAG_5 - GAG_4 - GAG_3,
           `26` = GAG_4 - GAG_2,
           `27` = GAG_2,
           `28` = GAG_3)
  
  
  # Finally, summarize the data by YEAR and MONTH (giving units of AF/month)
  gagDF <- gagDF |>
    group_by(YEAR, MONTH) |>
    summarize(across(matches("^[0-9]"), sum), .groups = "drop")
  
  
  # Return 'gagDF'
  return(gagDF)
  
}



mergeAndValidateFlows <- function (inqDF, gagDF, numBasins = 28) {
  
  # Combine 'inqDF' and 'gagDF' into a sub-basin flows tibble
  
  # All 28 sub-basins of the Russian River watershed should be represented here
  
  
  # Before combining the two variables, confirm that there are no missing values
  if (anyNA(inqDF)) {
    
    paste0("PRMS sub_inq - Missing Data Issue\n\n",
           "Processing the PRMS 'sub_inq' file led to it gaining \"NA\" ",
           "values. The source file was checked earlier, and it was not ",
           "missing any values. Please investigate the script.") |>
      errWrap() |>
      stop()
    
  }
  
  
  if (anyNA(gagDF)) {
    
    paste0("SRP GAG Files - Missing Data Issue\n\n",
           "Processing the SRP 'sub_inq' files led to 'gagDF' gaining \"NA\" ",
           "values. The source files were checked earlier, and they were not ",
           "missing any values. Please investigate the script.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Also, check that both variables contain "YEAR" and "MONTH"
  if (!all(c("YEAR", "MONTH") %in% names(inqDF)) ||
      !all(c("YEAR", "MONTH") %in% names(gagDF))) {
    
    paste0("'inqDF' and 'gagDF' - Missing Column Issue\n\n",
           "This procedure expects 'inqDF' and 'gagDF' to contain both a ",
           "\"YEAR\" and a \"MONTH\" column. However, that is not the case. ",
           "Please investigate the script, and update it accordingly.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Create a "Date" column in both 'inqDF' and 'gagDF'
  # Use "YEAR" and "MONTH", and set the day to be "1"
  inqDF <- inqDF |>
    mutate(Date = paste0(YEAR, "-", MONTH, "-01") |>
             as.Date(format = "%Y-%m-%d")) |>
    select(-c(YEAR, MONTH))
  
  
  gagDF <- gagDF |>
    mutate(Date = paste0(YEAR, "-", MONTH, "-01") |>
             as.Date(format = "%Y-%m-%d")) |>
    select(-c(YEAR, MONTH))
  
  
  
  # Merge 'inqDF' and 'gagDF' using the "Date" column
  flowDF <- inqDF |>
    full_join(gagDF, by = "Date",
              relationship = "one-to-one")
  
  
  # Sub-basins 1 through 28 should be represented among them (with no repeats)
  if (!all(1:numBasins %in% names(flowDF))) {
    
    paste0("Missing Sub-Basin Column(s)\n\n",
           "The combination of the PRMS \"sub_inq\" file and the SRP GAG ",
           "files should result in a data frame that contains data for ",
           numBasins, " sub-basins. Each sub-basin should have its own ",
           "column (named \"1\" through \"", numBasins, "\"). However, ",
           "that is not the case. Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Filter the dataset to start from the more recent start date
  # between 'inqDF' and 'gagDF'
  laterStart <- c(min(inqDF$Date), min(gagDF$Date)) |>
    max()
  
  
  flowDF <- flowDF |>
    filter(Date >= laterStart)
  
  
  # Verify that 'flowDF' does not contain any missing values
  if (anyNA(flowDF)) {
    
    paste0("Missing Data in Sub-Basin Flows\n\n",
           "The combination of the PRMS \"sub_inq\" file and the SRP GAG ",
           "files should result in a data frame that contains monthly flow ",
           "data for ", numBasins, " sub-basins from ", 
           min(flowDF$Date) |> format("%B %Y"), " to ", 
           max(flowDF$Date) |> format("%B %Y"), ". However, one or more ",
           "entries are \"NA\". Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # After that, confirm that no months are missing from 'flowDF'
  monthVec <- seq(from = min(flowDF$Date), 
                  to = max(flowDF$Date), 
                  by = "months")
  
  
  missingMonths <- monthVec[!(monthVec %in% flowDF$Date)]
  
  
  if (length(missingMonths)) {
    
    paste0("Missing Data in Sub-Basin Flows\n\n",
           "The combination of the PRMS \"sub_inq\" file and the SRP GAG ",
           "files should result in a data frame that contains monthly flow ",
           "data for ", numBasins, " sub-basins from ", 
           min(flowDF$Date) |> format("%B %Y"), " to ", 
           max(flowDF$Date) |> format("%B %Y"), ". However, ", 
           length(missingMonths), " month", 
           if_else(length(missingMonths) > 1, "s are", " is"), " missing (",
           missingMonths |> format("%B %Y") |> vec2QuotedStr(), "). ",
           "Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Output a warning if negative flows are detected in 'flowDF'
  if (map_lgl(flowDF, ~ any(. < 0)) |> any()) {
    
    # Get the specific sub-basins with negative flows
    negIndices <- flowDF |>
      map_lgl(~ !is.Date(.) & any(. < 0)) |>
      which()
    
    
    paste0("\nNegative flows detected in data for Subbasin",
           if_else(length(negIndices) > 1, "s", ""), " ",
           vec2QuotedStr(names(flowDF)[negIndices]), "!") |>
      errWrap() |>
      message()
    
    cat("\n")
    
  }
  
  
  # Finally, adjust the formatting of 'flowDF' and return it
  return(flowDF |>
           select(Date, all_of(as.character(1:numBasins))) |>
           arrange(Date))
  
}



adjustNegativeFlows <- function (flowDF) {
  
  # In each year-month pair of 'flowDF', 
  # if there are negative flows in a sub-basin, 
  # borrow flow from upstream locations to zero out those negative values
  
  
  # First check if there are any negative flows in 'flowDF'
  if (!any(select(flowDF, -Date) < 0)) {
    
    # If there are none, return 'flowDF' without any changes
    return(flowDF)
    
  }
  
  
  # Otherwise, read in a connectivity table for the watershed
  # It needs some preparations before it can be used
  # Those operations are performed in `getBasinConnectivity`
  connDF <- getBasinConnectivity()
  
  
  # Next, iterate through each of the rows in 'flowDF'
  for (i in 1:nrow(flowDF)) {
    
    # Each row of 'flowDF' is a different year-month pair
    
    # Check if any flows are negative for this iteration
    # If there are no negative flows, skip it
    if (!any(select(flowDF[i, ], -Date) < 0)) {
      
      next
      
    }
    
    
    # While there are negative flows in this row of 'flowDF',
    # keep going through this loop
    while (any(select(flowDF[i, ], -Date) < 0)) {
      
      # Check which columns in 'flowDF' have negative flows
      colIndex <- which(flowDF[i, ] < 0 & names(flowDF) != "Date")
      
      
      # Get the sub-basin numbers that correspond to the 
      # 'colIndex' values with negative flows
      basinNum <- names(flowDF)[colIndex] |>
        as.numeric()
      
      
      # Iterate through these negative flow basins
      for (j in 1:length(basinNum)) {
        
        # For this iteration's sub-basin,
        # Identify which sub-basin is upstream of it
        upstreamBasin <- connDF$BASIN_NUM[connDF$FLOWS_TO_NUM == basinNum[j]]
        
        
        # If no sub-basin is upstream of this negative flow sub-basin,
        if (length(upstreamBasin) == 0) {
          
          # Just zero out the sub-basin's flow
          flowDF[i, colIndex[j]] <- 0
          
          
        # Otherwise, if exactly one sub-basin is upstream of the basin
        } else if (length(upstreamBasin) == 1) {
          
          # Get the index in 'flowDF' where this upstream sub-basin is located
          upstreamIndex <- which(names(flowDF) == upstreamBasin)
          
          
          # Double-check that the index is valid
          if (length(upstreamIndex) == 0) {
            
            paste0("Sub-Basin ID Not Present in Raw Flows\n\n",
                   "For ", flowDF$Date[i], ", the script attempted to extract ",
                   "data related to Sub-Basin \"", upstreamBasin, "\". ",
                   "However, the procedure failed to find a matching column ",
                   "in the flow dataset.\n\n",
                   "This could be an error in the flow data or in the ",
                   "sub-basin connectivity table. Please investigate.") |>
              errWrap() |>
              stop()
            
          } else if (length(upstreamIndex) > 1) {
            
            paste0("Sub-Basin ID Not Present More Than Once In Raw Flows\n\n",
                   "For ", flowDF$Date[i], ", the script attempted to extract ",
                   "data related to Sub-Basin \"", upstreamBasin, "\". ",
                   "However, the procedure encountered multiple columns with ",
                   "this name in the flow dataset.\n\n",
                   "This is likely a script error. Please investigate.") |>
              errWrap() |>
              stop()
            
          }
          
          
          # Add the negative flow value to the upstream basin's value
          # (This is like "borrowing" flow from upstream 
          #  to zero out the negative flow)
          flowDF[i, upstreamIndex] <- 
            flowDF[i, upstreamIndex] + flowDF[i, colIndex[j]]
          
          
          # Then, set the negative flow to zero in the flagged basin
          flowDF[i, colIndex[j]] <- 0
          
          
        # If a sub-basin has multiple direct upstream sub-basins
        } else {
          
          # Split the negative flow between all upstream sub-basins
          # (i.e., "borrow" some flow from every sub-basin)
          
          # For each upstream sub-basin, get the TOTAL flow available in 
          # those sub-basins (including their respective upstream sub-basins)
          
          # Then calculate a ratio for each upstream sub-basin and use that 
          # to determine the flow contribution from each sub-basin in 
          # 'upstreamBasin' (i.e., the amount of flow from each sub-basin that
          # will offset the negative flow value)
          totalAvailability <- upstreamBasin |>
            map_dbl(~ calcTotalAvailableFlow(connDF, flowDF[i, ], .))
          
          
          # If the total available upstream flow is zero, just set the 
          # negative flow entry in 'flowDF' to zero
          if (all(totalAvailability == 0)) {
            
            # (This applies only if every upstream sub-basin has zero flow available)
            flowDF[i, colIndex[j]] <- 0
            
          } else {
            
            # Otherwise, calculate ratios based on 'totalAvailability'
            contributionRatios <- totalAvailability / sum(totalAvailability)
            
            
            # From each of the sub-basins that are upstream of 'basinNum',
            # take flow based on its corresponding ratio
            for (k in 1:length(upstreamBasin)) {
              
              # Locate one of the immediately upstream sub-basins in 'flowDF'
              upstreamIndex <- which(names(flowDF) == upstreamBasin[k])
              
              
              # Double-check that the index is valid
              if (length(upstreamIndex) == 0) {
                
                paste0("Sub-Basin ID Not Present in Raw Flows\n\n",
                       "For ", flowDF$Date[i], ", the script attempted to extract ",
                       "data related to Sub-Basin \"", upstreamBasin[k], "\". ",
                       "However, the procedure failed to find a matching column ",
                       "in the flow dataset.\n\n",
                       "This could be an error in the flow data or in the ",
                       "sub-basin connectivity table. Please investigate.") |>
                  errWrap() |>
                  stop()
                
              } else if (length(upstreamIndex) > 1) {
                
                paste0("Sub-Basin ID Not Present More Than Once In Raw Flows\n\n",
                       "For ", flowDF$Date[i], ", the script attempted to extract ",
                       "data related to Sub-Basin \"", upstreamBasin[k], "\". ",
                       "However, the procedure encountered multiple columns with ",
                       "this name in the flow dataset.\n\n",
                       "This is likely a script error. Please investigate.") |>
                  errWrap() |>
                  stop()
                
              }
              
              
              # Adjust the upstream sub-basin and "borrow" some flow to offset
              # the negative value in that sub-basin
              flowDF[i, upstreamIndex] <- 
                flowDF[i, upstreamIndex] + 
                contributionRatios[k] * flowDF[i, colIndex[j]]
              
              
              # The contribution ratios consider the flow available in the 
              # entire upstream path for each immediately upstream sub-basin
              
              # So, it is possible that the immediately upstream sub-basin will
              # get a negative flow value after this operation
              
              # That's okay though, because the "while" loop will keep going
              # as long as there are any negative flows
              
            }
            
            
            # After "borrowing" flow from each of the immediately upstream
            # sub-basins, set the negative flow in the flagged basin to zero 
            flowDF[i, colIndex[j]] <- 0
            
          } 
          
        } # End of conditional for multiple upstream sub-basins
        
      } # End of loop through negative sub-basins
      
    } # End of while loop for negative flows in a row of 'flowDF'
    
  } # End of loop through each year-month pair in 'flowDF'
  
  
  # Finally, return 'flowDF'
  return(flowDF)
  
}



getBasinConnectivity <- function () {
  
  # Read in a table that expresses the connectivity between sub-basins
  # in the watershed
  
  # Some additional columns will be included in this dataset to assist
  # with the procedure
  
  
  # Get the path to this file
  basinPath <- getFromControl_RR("SUBBASIN_CONNECTIVITY_CSV")
  
  
  # Use a validation function from another script
  functionStealer("W2_Russian_River/Scripts/RRW_019_Finalize_DWRAT_Inputs.R",
                  "validateBasins")
  
  
  # Read in the sub-basin file and apply the validation function too
  connDF <- basinPath |>
    getFile() |>
    validateBasins(basinPath)
  
  
  # 'flowDF' has its sub-basins as numbers (in the column names)
  # Meanwhile, 'connDF' has its sub-basin numbers stored within strings
  
  # On top of that, 'connDF' can have both mainstem and non-mainstem 
  # entries for a sub-basin
  
  
  # To make 'connDF' easier to work with, add three new columns:
  
  # (*) The first column will have the numeric portion of the "BASIN" label
  
  # (*) The second column will have the numeric portion of the "FLOWS_TO" label
  
  # (*) The third column will be an integer that states whether a "BASIN" value
  #     is mainstem or not. If it's a mainstem sub-basin, its value will be "1". 
  #     Otherwise, its value will be "0". 
  
  #     This will be useful when there are two rows for the same sub-basin
  #     (and one is mainstem while the other is not)
  
  #     When there are two options like this, we will take the *mainstem* one
  #     This is because the tributary option usually flows into its mainstem 
  #     counterpart anyways
  
  
  # Add the new columns to 'connDF'
  connDF <- connDF |>
    mutate(BASIN_NUM = str_extract(BASIN, "[0-9]+") |> as.numeric(),
           FLOWS_TO_NUM = str_extract(FLOWS_TO, "[0-9]+") |> as.numeric(),
           MAINSTEM_INT = if_else(MAINSTEM == "Y", 1, 0))
  
  
  # Then, group by sub-basin number and filter to one "BASIN" per "BASIN_NUM"
  # (So if there is a mainstem and tributary sub-basin option, consider the
  #  connectivity of the mainstem sub-basin only)
  # (Generally speaking, the tributaries drain into their mainstems anyways,
  #  so they wouldn't be helpful in this procedure)
  connDF <- connDF |>
    group_by(BASIN_NUM) |>
    filter(MAINSTEM_INT == max(MAINSTEM_INT)) |>
    ungroup() 
  
  
  # One more filter is needed to avoid circular connectivity
  # (i.e., a sub-basin shouldn't flow into itself)
  # It will trap the procedure in an infinite loop otherwise
  connDF <- connDF |>
    filter(BASIN_NUM != FLOWS_TO_NUM)
  
  
  # Another check for the Russian River is whether 'connDF' contains a 
  # connection between the Upper Russian River (sub-basins 1 through 13) and
  # the Lower Russian River (sub-basins 14 through 28)
  
  # Sub-basin 13 should flow into Sub-basin 17, 
  # if that connection is not already present
  if (which(connDF$BASIN_NUM == 13 & connDF$FLOWS_TO_NUM == 17) |> 
      length() == 0 &&
      !any("Y" %in% connDF$UPPER_RUSSIAN[connDF$BASIN_NUM > 13]) &&
      !any("N" %in% connDF$UPPER_RUSSIAN[connDF$BASIN_NUM < 14])) {
    
    # The second and third conditions add extra restrictions to make it 
    # clearer what this addition is about
    
    # In 'connDF', where the first 13 sub-basins are URR, and the remaining
    # sub-basins are LRR, connect sub-basin 13 to sub-basin 17
    connDF <- connDF |>
      bind_rows(tibble(BASIN_NUM = 13, FLOWS_TO_NUM = 17))
    
  }
  
  
  # One final check is needed before correcting the negative flows
  # Make sure there are no missing values in "BASIN_NUM" and "FLOWS_TO_NUM"
  if (anyNA(connDF$BASIN_NUM) || anyNA(connDF$FLOWS_TO_NUM)) {
    
    # Print out the problematic rows in 'connDF'
    print(connDF |> 
            filter(is.na(BASIN_NUM) | is.na(FLOWS_TO_NUM)))
    
    
    paste0("Missing Data in Sub-Basin Connectivity Matrix\n\n",
           "\"NA\" values were detected in the tibble containing sub-basin ",
           "connectivity information. The problematic row(s) are shown ",
           "above.\n\n",
           "This error is generally an indication of a script procedure error. ",
           "Please review the code and make adjustments as needed.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Finally, return 'connDF'
  return(connDF)
  
}



calcTotalAvailableFlow <- function (connDF, flowRow, startingBasin) {
  
  # Given 'flowRow', which contains flow values for each sub-basin,
  # and 'connDF', which expresses the connectivity between sub-basins,
  # determine the total available flow from 'startinBasin' and ALL of 
  # its upstream sub-basins
  
  
  # Define 'upstreamVec' to hold all upstream sub-basins
  # (starting with the one defined in 'startingBasin')
  upstreamVec <- startingBasin
  
  
  # This variable will contain the total available upstream flow
  # Start with the sum of the flow available in 'startingBasin'
  totalFlow <- flowRow[1, which(names(flowRow) == startingBasin)] |>
    sum()
  
  
  # While 'upstreamVec' still contains sub-basins
  while (length(upstreamVec) > 0) {
    
    # Identify which sub-basins are upstream of the one(s) that appear 
    # currently in 'upstreamVec'
    upstreamVec <- connDF$BASIN_NUM[which(connDF$FLOWS_TO_NUM %in% upstreamVec)]
    
    
    # Add to 'totalFlow' the flows of each of the sub-basins in 'upstreamVec'
    # (If 'upstreamVec' is empty, it will contribute "0" to 'totalFlow')
    totalFlow <- totalFlow +
      sum(flowRow[1, which(names(flowRow) %in% upstreamVec)])
    
  }
  
  
  # If 'totalFlow' is negative, return 0 as the total available upstream flow
  if (totalFlow < 0) {
    return(0)
  }
  
  
  # Otherwise, return 'totalFlow' if it's a positive number
  return(totalFlow)
  
}



#### Script Execution ####

mainProcedure()


# Clean up
base::remove(list = ls())

