# This script prepares the DAT file that is input into PRMS

# Earlier in the process, the downloaded meteorological dataset was formatted
# for integration into a PRMS input file

# It will now be merged into a long-running DAT file

# After that, predictions for the remainder of the water year will
# also be appended (this is an optional but enabled-by-default step)

# Depending on the time of year, the prediction method will differ:
#  (*) If 'endDate' is between October and February:
#      SPI-based predictions will be used
#  (*) If 'endDate' is between March and September AND this is the FIRST PRMS 
#      run in this period:
#        (1) PRMS will be run with the "SPI" approach
#        (2) The output will be collected and used to find the 
#            most similar water year
#        (3) PRMS will be run with the "Most Similar Water Year" approach
#  (*) If 'endDate' is between March and September:
#      The "Most Similar Water Year" approach will be used


# The script has several input files:
#  (1) "ProcessedData/Weather_Processed_Data_[startDate]_[endDate].csv"
#      The processed weather data

#  (2) A long-running DAT file (whose filepath is input into "MAIN_PRMS_DAT_FILE"
#      of the control file)

#  (3) A DAT file containing predictions for the current water year (its filepath
#      should be given in "PRMS_DAT_SPI_FILE" of the control file)


# A single output will be generated (in most cases):
#  (1) "ProcessedData/DAT_PRMS_[startDate]_[endDate].dat"
#      The final DAT file to use in the model run
#  (2) If the similar WY needs to be identified, components from that procedure
#      are generated as well


#### Setup ####

# Clear the environment
remove(list = ls())


# Import packages
source("Scripts/HLP_000_Load_Packages.R")


# Import shared functions
source("Scripts/HLP_001_Shared_Functions_Supply.R")


#### Functions ####

mainProcedure <- function (predictWY = TRUE) {
  
  cat("\n\n")
  cat("Starting 'RRS_008_Finalize_PRMS_Input.R'!\n")
  
  
  # Import the start and end date
  source("Scripts/HLP_002_Validate_and_Import_Data_Scraping_Bounds.R")
  
  
  # Confirm that a proper directory exists for model input and output files
  # The actual PRMS model files should have been successfully copied to
  # the "ProcessedData" folder too
  cat(paste0("[1/", if_else(predictWY, 5, 4),
             "]\tChecking directories...\n"))
  
  
  # Make sure that a hydrology folder was created earlier in the process
  folderFilePath <- paste0("ProcessedData/Hydrology_Output_Location_",
                           startDate, "_", endDate, ".txt")
  
  
  # Output an error message if 
  if (!file.exists(folderFilePath)) {
    
    stop(paste0("Model Run Folder Not Found\n\n",
                "A folder to store metadata and model inputs/outputs should ",
                "have been generated by an earlier script in this process. ",
                "An accompanying output was a text file that identifies its ",
                "location. However, it was not found. ",
                "Please run the previous scripts before running this one.\n\n",
                "The expected file was \"", folderFilePath, "\"") |>
           errWrap())
    
  }
  
  
  # Read in the text file to get the path to the actual folder
  dirPath <- read_lines(folderFilePath)[1]
  
  
  # Make sure that folder exists 
  if (!dir.exists(dirPath)) {
    
    stop(paste0("Model Run Folder Not Found\n\n",
                "A folder to store metadata and model inputs/outputs should ",
                "have been generated by an earlier script in this process. ",
                "However, it was not found. ",
                "Please run the previous scripts before running this one.\n\n",
                "The expected directory was \"", dirPath, "\"") |>
           errWrap())
    
  }
  
  
  # Also confirm that the "RR_PRMS" folder was copied to "ProcessedData"
  prmsPath <- "ProcessedData/RR_PRMS" |> normalizePath(mustWork = FALSE)
  
  
  # Make sure that folder exists 
  if (!dir.exists(prmsPath)) {
    
    stop(paste0("PRMS Folder Not Found\n\n",
                "A copy of the PRMS model files should have been added ",
                "to the \"ProcessedData\" folder in an earlier script. ",
                "However, it was not found. ",
                "Please run the previous scripts before running this one.\n\n",
                "The expected directory was \"", prmsPath, "\"") |>
           errWrap())
    
  }
  
  
  cat("\tDone!\n\n")
  
  
  cat(paste0("[2/", if_else(predictWY, 5, 4),
             "]\tLoading meteorological data and long-running DAT file...\n"))
  
  
  # Read in two of the main input files
  # (The PRMS Meteorological CSV and the primary DAT file)
  filePaths <- c(paste0("ProcessedData/PRMS_Meteorological_", startDate,
                        "_", endDate, ".csv"),
                 getFromSupplyControl_RR("MAIN_PRMS_DAT_FILE"))
  
  
  # Verify that the meteorological CSV file exists
  # (This is a sign that the prior scripts completed their procedure)
  if (!file.exists(filePaths[1])) {
    
    stop(paste0("Meteorological CSV Not Found\n\n",
                "The meteorological CSV file, which would be generated by an ",
                "earlier script in this process, was not found. ",
                "Please run the previous scripts before running this one.\n\n",
                "The expected file was \"", filePaths[1], "\"") |>
           errWrap())
    
  }
  
  
  # Read in the two files next
  meteorDF <- getDelim(filePaths[1], ",")
  
  primaryDAT <- getFile(filePaths[2], "\t")
  
  
  # Validate the primary DAT file next
  # (This function also adds a "DATE" column to 'primaryDAT')
  # (That column enables matching with 'meteorDF')
  primaryDAT <- validateInputDAT(primaryDAT, "MAIN_PRMS_DAT_FILE",
                                 names(meteorDF)[names(meteorDF) != "DATE"],
                                 startDate, endDate, datType = "Main")
  
  
  # Output messages
  cat("\tDone!\n\n")
  
  
  cat(paste0("[3/", if_else(predictWY, 5, 4),
             "]\tMerging the two files together...\n"))
  
  
  # Merge 'primaryDAT' with 'meteorDF'
  # (Overlapping dates with 'startDate' are removed from 'primaryDAT')
  # (Also, "YEAR", "MONTH", "DAY", "HOUR", "MINUTE", and "SECOND" are 
  #  added to 'meteorDF')
  mergedDAT <- primaryDAT |> 
    filter(DATE < startDate) |>
    bind_rows(meteorDF |>
                mutate(YEAR = year(DATE), MONTH = month(DATE), DAY = day(DATE),
                       HOUR = 0, MINUTE = 0, SECOND = 0))
  
  
  cat("\tDone!\n\n")
  
  
  # After that, if 'predictWY' is TRUE, add predictions for the current water year
  if (predictWY) {
    
    cat("[4/5]\tAppending forecasted predictions for the current water year...\n")
    
    
    mergedDAT <- predictCurrentWY(mergedDAT, startDate, endDate, 
                                  names(meteorDF)[names(meteorDF) != "DATE"],
                                  dirPath, prmsPath)
    
    
    cat("\tDone!\n\n")
    
  }
  
  
  cat(paste0("[", if_else(predictWY, "5/5", "4/4"),
             "]\tSaving output...\n"))
  
  
  # Finally, write 'mergedDAT' to a file
  # It will be stored in both the "RR_PRMS" folder and the model run 
  # output folder 
  mergedDAT |>
    outputDAT()
  
  
  cat("\tDone!\n\n")
  
  
  # Output a completion message
  cat(col_green("\n'RRS_008_Finalize_PRMS_Input.R' is complete!\n\n"))
  
  
  # Return nothing
  return(invisible(NULL))
  
}



validateInputDAT <- function (datFile, sourceField, prmsCols,
                              startDate, endDate, datType = "Main") {
  
  # Verify the formatting of a DAT file for PRMS
  # This function will be applied to both the long-running meteorological
  # DAT file as well as the SPI DAT file
  
  # 'datType' will be used if certain checks are specific to 
  # the main DAT file, the SPI DAT file, or the final DAT file
  
  
  if (!(datType %in% c("Main", "SPI", "Final"))) {
    
    stop(paste0("Script Error - Unknown Value for 'datType'\n\n",
                "The input variable 'datType' must be one of three ",
                "values (", 
                vec2QuotedStr(c("Main", "SPI", "Final")), "). \"",
                datType, "\" is not a recognized value. Please revise ",
                "the script.") |>
           errWrap())
    
  }
  
  
  
  # First, check that the date- and time-related fields are present
  datetimeCols <- c("YEAR", "MONTH", "DAY", "HOUR", "MINUTE", "SECOND")
  
  
  if (anyFalse(datetimeCols %in% names(datFile))) {
    
    # Identify the missing columns
    missingCols <- which(!(datetimeCols %in% names(datFile)))
    
    
    stop(paste0("DAT File - Column Issue\n\n",
                "The ",
                if_else(checkForMainDAT, " primary ", " SPI "),
                "input file for PRMS does not have all of the required ",
                "datetime columns (",
                vec2QuotedStr(datetimeCols[missingCols]), ").\n\n",
                "The DAT file must contain headers that match the names in ",
                "the meteorological CSV (\"PRMS_Meteorological_", startDate, 
                "_", endDate, ".csv\"). Please correct this file and try ",
                "again.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap() |>
           str_replace("(does not)", col_red("\\1")))
    
  }
  
  
  # After that, perform a similar check for the PRMS columns
  if (anyFalse(prmsCols %in% names(datFile))) {
    
    # Identify the missing columns
    missingCols <- which(!(prmsCols %in% names(datFile)))
    
    
    stop(paste0("DAT File - Column Issue\n\n",
                "The ",
                if_else(checkForMainDAT, " primary ", " SPI "),
                "input file for PRMS does not have all of the required ",
                "PRMS columns (",
                vec2QuotedStr(prmsCols[missingCols]), ").\n\n",
                "The number of precipitation and temperature columns (and their ",
                "names) must match exactly with the meteorological CSV ",
                "(\"PRMS_Meteorological_", startDate, "_", endDate, ".csv\"). ",
                "Please correct this file and try again.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap() |>
           str_replace("(does not)", col_red("\\1")))
    
  }
  
  
  # For the next checks, give 'datFile' a "DATE" column
  datFile <- datFile |>
    mutate(DATE = paste0(YEAR, "-", MONTH, "-", DAY) |> 
             as.Date(format = "%Y-%m-%d"))
  
  
  # Next, get the start and end dates of the DAT file
  datRange <- datFile |>
    select(DATE) |>
    filter(DATE == min(DATE) | DATE == max(DATE)) |>
    arrange(DATE)
  
  
  # Make sure there are no missing dates in 'datFile'
  expectedDates <- seq(from = datRange$DATE[1],
                       to = datRange$DATE[2],
                       by = "days")
  
  
  # Check for missing dates
  if (anyFalse(expectedDates %in% datFile$DATE)) {
    
    # Identify the missing dates
    missingDates <- which(!(expectedDates %in% datFile$DATE))
    
    
    stop(paste0("DAT File - Date Issue\n\n",
                "The ",
                if_else(checkForMainDAT, " primary ", " SPI "),
                "input file for PRMS is missing data for ", 
                length(missingDates), " day",
                if_else(length(missingDates) > 1, "s", ""), " (", 
                vec2QuotedStr(expectedDates[missingDates]), "). Please correct ",
                "this file and try again.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap() |>
           str_replace("(does not)", col_red("\\1")))
    
  }
  
  
  # Similarly, check for mismatches between 'datFile' and 'expectedDates'
  # (Because of the previous check, this error will likely occur if a date is 
  #  duplicated in the DAT file)
  if (nrow(datFile) != length(expectedDates)) {
    
    # If the cause is a duplicate error, identify the duplicated dates
    dupDates <- table(datFile$DATE)
    
    dupDates <- dupDates[dupDates > 1]
    
    
    if (length(dupDates) > 0) {
      
      stop(paste0("DAT File - Date Issue\n\n",
                  "The ",
                  if_else(checkForMainDAT, " primary ", " SPI "),
                  "input file for PRMS has multiple rows for the same date",
                  if_else(length(dupDates) > 1, "s", ""), " (",
                  vec2QuotedStr(names(dupDates)), ").\n\n", 
                  "Please correct this issue. Every date should have exactly ",
                  "one row in the DAT file.\n\n", 
                  if_else(datType != "Final",
                          paste0("(This error occurred for '", 
                                 getFromSupplyControl_RR(sourceField), "')"),
                          paste0("Please investigate the component ",
                                 "DAT files."))) |>
             errWrap() |>
             str_replace("(does not)", col_red("\\1")))
      
      # If this error occurred because of some other unknown issue,  
      # use this error message instead
    } else {
      
      stop(paste0("DAT File - Data Issue\n\n",
                  "The ",
                  if_else(checkForMainDAT, " primary ", " SPI "),
                  "input file for PRMS has an unknown data issue. The number ",
                  "of rows in the dataset does not match the number of days ",
                  "between the start and end dates in that file. Please ",
                  "investigate.\n\n", 
                  if_else(datType != "Final",
                          paste0("(This error occurred for '", 
                                 getFromSupplyControl_RR(sourceField), "')"),
                          paste0("Please investigate the component ",
                                 "DAT files."))) |>
             errWrap() |>
             str_replace("(unknown)", col_red("\\1")))
      
    }
    
  }
  
  
  # If there are missing entries in the DAT file, alert the user
  if (anyNA(datFile)) {
    
    # Output the locations of missing values
    cat("\n\n\"NA\" Entries:\n")
    print(which(is.na(datFile), arr.ind = TRUE))
    
    stop(paste0("DAT File - Missing Data Issue\n\n",
                if_else(sum(is.na(datFile)) > 1, 
                        "Missing values were ",
                        "A missing value was "), 
                " detected in the DAT file (see the above message for locations",
                "). Please correct the file.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap())
    
  }
  
  
  # For the next check, look for a logistical issue for the primary DAT file
  # (The one with long-running meteorological data)
  # 'startDate' can overlap with 'datFile', but if not, there should be no gaps
  # 'startDate' for the meteorological dataset should be, at most, on the next day
  # after the end of the dates in 'primaryDAT'
  if (datType == "Main" && startDate > max(datFile$DATE) + 1) {
    
    stop(paste0("Main DAT File and 'startDate' - Data Gap Issue\n\n",
                "Because the meteorological dataset starts at ", startDate,
                ", there will be a data gap issue with this DAT file. Its ",
                "latest date is ", max(datFile$DATE), ", which means ",
                "that not all dates will have data when running PRMS with ",
                "these files. Please adjust either the DAT file or 'startDate' ",
                "in the control script.\n\n",
                "(This error occurred for '", 
                getFromSupplyControl_RR(sourceField), "')") |>
           errWrap())
    
  }
  
  
  # The final checks are specific to the SPI DAT file 
  if (datType == "SPI") {
    
    # Get the bounds of the water year being modeled
    wyBounds <- getModeledWY(endDate)
    
    
    # The predicted values in 'datFile' must extend to the end of the water year
    if (max(datFile$DATE) < wyBounds[2]) {
      
      stop(paste0("Incomplete SPI DAT File - End of Water Year\n\n",
                  "The DAT file that contains predictions for the current water ",
                  "year is missing data. It does not extend to the end of the ",
                  "water year (\"", wyBounds[2], "\"). Please adjust ",
                  "this file.\n\n",
                  "(This error occurred for '", 
                  getFromSupplyControl_RR(sourceField), "')") |>
             errWrap())
      
    # Similarly, if 'endDate' is an earlier date than the start of 'datFile', 
    # there should be no gap between then
    } else if (endDate + 1 < min(datFile$DATE)) {
      
      stop(paste0("SPI DAT File and 'endDate' - Data Gap Issue\n\n",
                  "Because the meteorological dataset ends at ", endDate,
                  ", there will be a data gap issue with this DAT file. Its ",
                  "earliest date is ", min(datFile$DATE), ", which means ",
                  "that not all dates will have data when running PRMS with ",
                  "these files. Please adjust either the DAT file or 'endDate' ",
                  "in the control script.\n\n",
                  "(This error occurred for '", 
                  getFromSupplyControl_RR(sourceField), "')") |>
             errWrap())
      
    }
    
  }
  
  
  # If there are no issues, return 'datFile'
  # (It now has a "DATE" column)
  return(datFile |> arrange(DATE))
  
}



predictCurrentWY <- function (mergedDAT, startDate, endDate, prmsCols,
                              dirPath, prmsPath) {
  
  # Based on 'endDate', apply different methods to select predictions 
  # to append to 'mergedDAT'
  
  
  # For October - February, use the SPI prediction method
  if (month(endDate) < 3 || month(endDate) > 9) {
    
    # At this point in time, insufficient precipitation data is available
    # Predictions using the Standard Precipitation Index (SPI) will be
    # appended to the DAT file
    spiDAT <- getFromSupplyControl_RR("PRMS_DAT_SPI_FILE") |>
      getFile("\t")
    
    
    # Validate the DAT file before continuing
    spiDAT <- validateInputDAT(spiDAT, "PRMS_DAT_SPI_FILE", prmsCols, 
                               startDate, endDate, datType = "SPI")
    
    
    # Filter 'spiDAT' to dates after the last date in 'mergedDAT'
    # Then, append it to 'mergedDAT'
    finalDAT <- mergedDAT |>
      bind_rows(spiDAT |> filter(DATE > max(mergedDAT$DATE)))
    
    
    # Update the metadata file next
    updateMetadata_DAT(dirPath, "SPI")
    
    
    
  # If 'endDate' is within March - September, the most similar WY will be used
  } else {
    
    # Identify the most similar water year using a PRMS run
    
    
    # First run PRMS to the 
    
    
    
    
  }
  
  
  
  # Make sure the "Runoff" columns all contain "1" for every row
  # (This is more of a concern if SPI data is appended because that file 
  #  may lack the "Runoff" columns)
  # (That would cause "NA" entries to appear)
  finalDAT <- finalDAT |>
    mutate(across(starts_with("Runoff"), ~replace_na(., 1)))
  
  
  
  # Perform a few checks on 'finalDAT'
  validateInputDAT(finalDAT, sourceField = NULL, prmsCols,
                   startDate, endDate, datType = "Final")
  
  
  # Then, return 'finalDAT'
  return(finalDAT)
  
}



getModeledWY <- function (endDate) {
  
  # Based on the value of 'endDate', identify the water year being modeled
  # Then, return a vector of dates containing the bounds of that water year
  
  
  # (1) Determining the starting bound:
  
  #     If 'endDate' is between January and September (inclusive), the water year
  #     matches the calendar year in 'endDate'
  
  #     If that is true, then the water year starts on October 1st of the 
  #     preceding calendar year
  
  #     (e.g., if it's 2026-03-09, we are modeling WY2026, which began on 
  #      2025-10-01)
  
  #     If 'endDate' is in the October - December range, the water year is the
  #     calendar year plus one
  
  #     In addition, the start of the water year is October 1st of the same year
  #     as 'endDate'
  
  #     (e.g., if it's 2024-12-12, we are modeling WY2025, which began on 
  #      2024-10-01)
  
  
  # (2) Determining the ending bound:
  
  #     If 'endDate' is between January and September (inclusive), the water year
  #     matches the calendar year in 'endDate'
  
  #     If that is true, then the water year ends on September 30th of the 
  #     current calendar year
  
  #     (e.g., if it's 2026-03-09, we are modeling WY2026, which ends on 
  #      2026-09-30)
  
  #     If 'endDate' is in the October - December range, the water year is the
  #     calendar year plus one
  
  #     In addition, the end of the water year is September 30th of the next year
  #     after the year in 'endDate'
  
  #     (e.g., if it's 2024-12-12, we are modeling WY2025, which ends on 
  #      2025-09-30)
  
  
  # Get the start and end dates of the water year
  # Then, return them as a vector of dates
  return(c(start = if_else(month(endDate) < 10,
                           paste0(year(endDate) - 1, "-10-01"),
                           paste0(year(endDate), "-10-01")),
           end = if_else(month(endDate) < 10,
                         paste0(year(endDate), "-09-30"),
                         paste0(year(endDate) + 1, "-09-30"))) |>
           as.Date(format = "%Y-%m-%d"))
  
}



updateMetadata_DAT <- function (dirPath, predictionMethod) {
  
  # 
  
  
  # 
  metaPath <- paste0(dirPath, "/metadata.csv") |>
    normalizePath() 
  
  
  metaDF <- getFile(metaPath, fileType = "CSV")
  
  
  metaDF <- metaDF |>
    mutate(WY_PREDICTION_METHOD = predictionMethod)
  
  
  metaDF |> 
    writeOutput(metaPath, quietly = TRUE)
  
  
  return(invisible(NULL))
  
}


#### Script Execution ####

mainProcedure()


# Clean up
remove(list = ls())


