# This script prepares the DAT file that is input into SRP 
# The control file and batch file in SRP are setup as well

# Earlier in the process, the downloaded meteorological dataset was formatted
# for integration into a SRP input file

# It will now be merged into a long-running DAT file

# After that, predictions for the remainder of the water year will
# also be appended (this is an optional but enabled-by-default step)

# Depending on the time of year, the prediction method will differ:

#  (*) If 'endDate' is between October and February:
#      SPI-based predictions will be used

#  (*) If 'endDate' is between March and September:
#        (1) PRMS will be run with the "SPI" approach
#        (2) The output will be collected and used to find the 
#            most similar water year
#        (3) PRMS will be run with the "Most Similar Water Year" approach


# The script has several input files:
#  (1) "ProcessedData/Weather_Processed_Data_[startDate]_[endDate].csv"
#      The processed weather data

#  (2) A long-running DAT file (whose filepath is input into "MAIN_PRMS_DAT_FILE"
#      of the control file)

#  (3) A DAT file containing predictions for the current water year (its filepath
#      should be given in "PRMS_DAT_SPI_FILE" of the control file)

#  (4) From the PRMS model files, the "prms_rr.control" file will be edited

#  (5) Similarly, the model's "run.bat" file will be updated as well


# A single output will be generated in all cases, and additional outputs will 
# be included whenever the "Similar WY" procedure is executed: 

#  (1) "ProcessedData/DAT_PRMS_[startDate]_[endDate].dat"
#      The final DAT file to use in the model run
#      (This file is also copied to the "RR_PRMS" folder as "RR_PRMS_Input.dat")

#  (2) If the similar WY needs to be identified, components from that procedure
#      are generated as well

# Technically, "prms_rr.control" and "run.bat" are setup by this script as well
# (Though, the copied "RR_PRMS" contents will be deleted at the end of the model
#  run procedure, so they will not stick around for long)


#### Setup ####

# Clear the environment
remove(list = ls())


# Import packages
source("Scripts/HLP_000_Load_Packages.R")


# Import shared functions
source("Scripts/HLP_001_Shared_Functions_Supply.R")


#### Functions ####

mainProcedure <- function (predictWY = TRUE) {
  
  cat("\n\n")
  cat("Starting 'RRS_013_Finalize_SRP_Input.R'!\n")
  
  
  # Import the start and end date
  source("Scripts/HLP_002_Validate_and_Import_Data_Scraping_Bounds.R")
  
  
  # Confirm that a proper directory exists for model input and output files
  # The actual PRMS model files should have been successfully copied to
  # the "ProcessedData" folder too
  cat(paste0("[1/", if_else(predictWY, 5, 4),
             "]\tChecking directories...\n"))
  
  
  # Check for the directory that contains metadata and model input/output files
  dirPath <- checkForHydroFolder(startDate, endDate)
  
  
  # Also confirm that the "SRPHM_update_ag" folder was copied to "ProcessedData"
  srpPath <- checkForSRP()
  
  
  cat("\tDone!\n\n")
  
  
  cat(paste0("[2/", if_else(predictWY, 5, 4),
             "]\tLoading meteorological data and long-running DAT file...\n"))
  
  
  # Read in two of the main input files
  # (The PRMS Meteorological CSV and the primary DAT file)
  filePaths <- c(paste0("ProcessedData/SRP_Meteorological_", startDate,
                        "_", endDate, ".csv"),
                 getFromSupplyControl_RR("MAIN_SRP_DAT_FILE"))
  
  
  # Verify that the meteorological CSV file exists
  # (This is a sign that the prior scripts completed their procedure)
  if (!file.exists(filePaths[1])) {
    
    stop(paste0("Meteorological CSV Not Found\n\n",
                "The meteorological CSV file, which would be generated by an ",
                "earlier script in this process, was not found. ",
                "Please run the previous scripts before running this one.\n\n",
                "The expected file was \"", filePaths[1], "\"") |>
           errWrap())
    
  }
  
  
  # Read in the two files next
  meteorDF <- getDelim(filePaths[1], ",")
  
  primaryDAT <- getFile(filePaths[2], "\t")
  
  
  # Validate the primary DAT file next
  # (This function also adds a "DATE" column to 'primaryDAT')
  # (That column enables matching with 'meteorDF')
  primaryDAT <- validateInputDAT(primaryDAT, "MAIN_PRMS_DAT_FILE",
                                 names(meteorDF)[names(meteorDF) != "DATE"],
                                 startDate, endDate, datType = "Main")
  
  
  # Output messages
  cat("\tDone!\n\n")
  
  
  cat(paste0("[3/", if_else(predictWY, 5, 4),
             "]\tMerging the two files together...\n"))
  
  
  # Merge 'primaryDAT' with 'meteorDF'
  # (Overlapping dates with 'startDate' are removed from 'primaryDAT')
  # (Also, "YEAR", "MONTH", "DAY", "HOUR", "MINUTE", and "SECOND" are 
  #  added to 'meteorDF')
  mergedDAT <- primaryDAT |> 
    filter(DATE < startDate) |>
    bind_rows(meteorDF |>
                mutate(YEAR = year(DATE), MONTH = month(DATE), DAY = day(DATE),
                       HOUR = 0, MINUTE = 0, SECOND = 0))
  
  
  cat("\tDone!\n\n")
  
  
  # After that, if 'predictWY' is TRUE, add predictions for the current water year
  if (predictWY) {
    
    cat("[4/5]\tAppending forecasted predictions for the current water year...\n")
    
    
    mergedDAT <- predictCurrentWY(mergedDAT, startDate, endDate, 
                                  names(meteorDF)[names(meteorDF) != "DATE"],
                                  dirPath, srpPath, filePaths[2])
    
    
    cat("\tDone!\n\n")
    
    
    # Even if predictions will not be used, update metadata in the hydrology folder
  } else {
    
    updateMetadata_DAT(dirPath, NA_character_, filePaths[2], endDate)
    
  }
  
  
  cat(paste0("[", if_else(predictWY, "5/5", "4/4"),
             "]\tSaving output...\n"))
  
  
  # Finally, write 'mergedDAT' to a file
  # It will be stored in both the "RR_PRMS" folder and the model run 
  # output folder 
  mergedDAT |>
    outputDAT(startDate, endDate, dirPath, srpPath, predictWY)
  
  
  cat("\tDone!\n\n")
  
  
  # Output a completion message
  cat(col_green("\n'RRS_013_Finalize_SRP_Input.R' is complete!\n\n"))
  
  
  # Return nothing
  return(invisible(NULL))
  
}



checkForHydroFolder <- function (startDate, endDate) {
  
  # Verify that previous scripts were run successfully and that a hydrology 
  # folder was created 
  
  
  # Get the text file that contains the path to the hydrology folder
  folderFilePath <- paste0("ProcessedData/Hydrology_Output_Location_",
                           startDate, "_", endDate, ".txt")
  
  
  # Output an error message if the file was not found
  if (!file.exists(folderFilePath)) {
    
    stop(paste0("Model Run Folder Not Found\n\n",
                "A folder to store metadata and model inputs/outputs should ",
                "have been generated by an earlier script in this process. ",
                "An accompanying output was a text file that identifies its ",
                "location. However, it was not found. ",
                "Please run the previous scripts before running this one.\n\n",
                "The expected file was \"", folderFilePath, "\"") |>
           errWrap())
    
  }
  
  
  # Read in the text file to get the path to the actual folder
  dirPath <- read_lines(folderFilePath)[1]
  
  
  # Make sure that folder exists 
  if (!dir.exists(dirPath)) {
    
    stop(paste0("Model Run Folder Not Found\n\n",
                "A folder to store metadata and model inputs/outputs should ",
                "have been generated by an earlier script in this process. ",
                "However, it was not found. ",
                "Please run the previous scripts before running this one.\n\n",
                "The expected directory was \"", dirPath, "\"") |>
           errWrap())
    
  }
  
  
  # Confirm that the metadata CSV file exists too
  metaPath <- paste0(dirPath, "/metadata.csv") |>
    normalizePath(mustWork = FALSE)
  
  
  if (!file.exists(metaPath)) {
    
    stop(paste0("Missing Metadata File\n\n",
                "When the hydrology folder was setup, a metadata CSV file ", 
                "should have been generated. However, it was not found. ",
                "Please investigate.\n\n",
                "(This error occurred for \"", metaPath, "\")") |>
           errWrap())
    
  }
  
  
  # If there are no issues, return 'dirPath'
  return(dirPath)
  
}



checkForSRP <- function () {
  
  # In a prior script, SRP model files were copied to the "ProcessedData" folder
  # Verify that it exists
  
  
  # The expected path of the "SRPHM_update_ag" folder
  srpPath <- "ProcessedData/SRPHM_update_ag" |> normalizePath(mustWork = FALSE)
  
  
  # Make sure that that folder exists 
  if (!dir.exists(srpPath)) {
    
    stop(paste0("SRP Folder Not Found\n\n",
                "A copy of the SRP model files should have been added ",
                "to the \"ProcessedData\" folder in an earlier script. ",
                "However, it was not found. ",
                "Please run the previous scripts before running this one.\n\n",
                "The expected directory was \"", srpPath, "\"") |>
           errWrap())
    
  }
  
  
  # Also confirm that the control file for SRP exists
  controlPath <- paste0(srpPath, "/SRPHM_update.control") |> 
    normalizePath(mustWork = FALSE)
  
  
  if (!file.exists(controlPath)) {
    
    stop(paste0("Missing SRP Control File\n\n",
                "When the SRP folder was copied into the \"ProcessedData\" ", 
                "folder, a control file was present in the folder. ",
                "However, it cannot be found now. Please investigate.\n\n",
                "(This error occurred for \"", controlPath, "\")") |>
           errWrap())
    
  }
  
  
  # Return 'srpPath'
  return(srpPath)
  
}



validateInputDAT <- function (datFile, sourceField, prmsCols,
                              startDate, endDate, datType = "Main") {
  
  # Verify the formatting of a DAT file for PRMS
  # This function will be applied to both the long-running meteorological
  # DAT file as well as the SPI DAT file
  
  # 'datType' will be used if certain checks are specific to 
  # the main DAT file, the SPI DAT file, or the final DAT file
  
  
  if (!(datType %in% c("Main", "SPI", "Final"))) {
    
    stop(paste0("Script Error - Unknown Value for 'datType'\n\n",
                "The input variable 'datType' must be one of three ",
                "values (", 
                vec2QuotedStr(c("Main", "SPI", "Final")), "). \"",
                datType, "\" is not a recognized value. Please revise ",
                "the script.") |>
           errWrap())
    
  }
  
  
  # First, check that the date- and time-related fields are present
  datetimeCols <- c("YEAR", "MONTH", "DAY", "HOUR", "MINUTE", "SECOND")
  
  
  if (anyFalse(datetimeCols %in% names(datFile))) {
    
    # Identify the missing columns
    missingCols <- which(!(datetimeCols %in% names(datFile)))
    
    
    stop(paste0("DAT File - Column Issue\n\n",
                "The ", datType,
                " input file for PRMS does not have all of the required ",
                "datetime columns (",
                vec2QuotedStr(datetimeCols[missingCols]), ").\n\n",
                "The DAT file must contain headers that match the names in ",
                "the meteorological CSV (\"PRMS_Meteorological_", startDate, 
                "_", endDate, ".csv\"). Please correct this file and try ",
                "again.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap() |>
           str_replace("(does not)", col_red("\\1")))
    
  }
  
  
  # After that, perform a similar check for the PRMS columns
  if (anyFalse(prmsCols %in% names(datFile))) {
    
    # Identify the missing columns
    missingCols <- which(!(prmsCols %in% names(datFile)))
    
    
    stop(paste0("DAT File - Column Issue\n\n",
                "The ", datType,
                " input file for PRMS does not have all of the required ",
                "PRMS columns (",
                vec2QuotedStr(prmsCols[missingCols]), ").\n\n",
                "The number of precipitation and temperature columns (and their ",
                "names) must match exactly with the meteorological CSV ",
                "(\"PRMS_Meteorological_", startDate, "_", endDate, ".csv\"). ",
                "Please correct this file and try again.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap() |>
           str_replace("(does not)", col_red("\\1")))
    
  }
  
  
  # Make sure all fields are numeric next
  if (anyFalse(map_lgl(datFile[names(datFile) != "DATE"], is.numeric))) {
    
    # Identify the non-numeric columns
    nonNumCols <- which(!map_lgl(datFile, is.numeric))
    
    
    # Exclude the "DATE" column from this list, if it's present in 'datFile'
    if ("DATE" %in% names(datFile)) {
      
      nonNumCols <- nonNumCols |>
        base::setdiff(which(names(datFile) == "DATE"))
      
    }
    
    
    stop(paste0("DAT File - Column Type Issue\n\n",
                "Every column in the ", datType, " input file for PRMS is ",
                "expected to be numeric. However, ", length(nonNumCols),
                " column", if_else(length(nonNumCols) > 1, "s have", " has"), 
                " a different type (",
                vec2QuotedStr(names(datFile)[nonNumCols]), ").\n\n",
                "Please correct this file and try again.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap() |>
           str_replace("(does not)", col_red("\\1")))
    
  }
  
  
  # For the next checks, give 'datFile' a "DATE" column
  datFile <- datFile |>
    mutate(DATE = paste0(YEAR, "-", MONTH, "-", DAY) |> 
             as.Date(format = "%Y-%m-%d"))
  
  
  # Next, get the start and end dates of the DAT file
  datRange <- datFile |>
    select(DATE) |>
    filter(DATE == min(DATE) | DATE == max(DATE)) |>
    arrange(DATE)
  
  
  # Make sure there are no missing dates in 'datFile'
  expectedDates <- seq(from = datRange$DATE[1],
                       to = datRange$DATE[2],
                       by = "days")
  
  
  # Check for missing dates
  if (anyFalse(expectedDates %in% datFile$DATE)) {
    
    # Identify the missing dates
    missingDates <- which(!(expectedDates %in% datFile$DATE))
    
    
    stop(paste0("DAT File - Date Issue\n\n",
                "The ", datType,
                " input file for PRMS is missing data for ", 
                length(missingDates), " day",
                if_else(length(missingDates) > 1, "s", ""), " (", 
                vec2QuotedStr(expectedDates[missingDates]), "). Please correct ",
                "this file and try again.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap() |>
           str_replace("(does not)", col_red("\\1")))
    
  }
  
  
  # Similarly, check for mismatches between 'datFile' and 'expectedDates'
  # (Because of the previous check, this error will likely occur if a date is 
  #  duplicated in the DAT file)
  if (nrow(datFile) != length(expectedDates)) {
    
    # If the cause is a duplicate error, identify the duplicated dates
    dupDates <- table(datFile$DATE)
    
    dupDates <- dupDates[dupDates > 1]
    
    
    if (length(dupDates) > 0) {
      
      stop(paste0("DAT File - Date Issue\n\n",
                  "The ", datType,
                  " input file for PRMS has multiple rows for the same date",
                  if_else(length(dupDates) > 1, "s", ""), " (",
                  vec2QuotedStr(names(dupDates)), ").\n\n", 
                  "Please correct this issue. Every date should have exactly ",
                  "one row in the DAT file.\n\n", 
                  if_else(datType != "Final",
                          paste0("(This error occurred for '", 
                                 getFromSupplyControl_RR(sourceField), "')"),
                          paste0("Please investigate the component ",
                                 "DAT files."))) |>
             errWrap() |>
             str_replace("(does not)", col_red("\\1")))
      
      # If this error occurred because of some other unknown issue,  
      # use this error message instead
    } else {
      
      stop(paste0("DAT File - Data Issue\n\n",
                  "The ", datType,
                  " input file for PRMS has an unknown data issue. The number ",
                  "of rows in the dataset does not match the number of days ",
                  "between the start and end dates in that file. Please ",
                  "investigate.\n\n", 
                  if_else(datType != "Final",
                          paste0("(This error occurred for '", 
                                 getFromSupplyControl_RR(sourceField), "')"),
                          paste0("Please investigate the component ",
                                 "DAT files."))) |>
             errWrap() |>
             str_replace("(unknown)", col_red("\\1")))
      
    }
    
  }
  
  
  # If there are missing entries in the DAT file, alert the user
  if (anyNA(datFile)) {
    
    # Output the locations of missing values
    cat("\n\n\"NA\" Entries:\n")
    print(which(is.na(datFile), arr.ind = TRUE))
    
    stop(paste0("DAT File - Missing Data Issue\n\n",
                if_else(sum(is.na(datFile)) > 1, 
                        "Missing values were ",
                        "A missing value was "), 
                " detected in the DAT file (see the above message for locations",
                "). Please correct the file.\n\n", 
                if_else(datType != "Final",
                        paste0("(This error occurred for '", 
                               getFromSupplyControl_RR(sourceField), "')"),
                        paste0("Please investigate the component DAT files."))) |>
           errWrap())
    
  }
  
  
  # For the next check, look for a logistical issue for the primary DAT file
  # (The one with long-running meteorological data)
  # 'startDate' can overlap with 'datFile', but if not, there should be no gaps
  # 'startDate' for the meteorological dataset should be, at most, on the next day
  # after the end of the dates in 'primaryDAT'
  if (datType == "Main" && startDate > max(datFile$DATE) + 1) {
    
    stop(paste0("Main DAT File and 'startDate' - Data Gap Issue\n\n",
                "Because the meteorological dataset starts at ", startDate,
                ", there will be a data gap issue with this DAT file. Its ",
                "latest date is ", max(datFile$DATE), ", which means ",
                "that not all dates will have data when running PRMS with ",
                "these files. Please adjust either the DAT file or 'startDate' ",
                "in the control script.\n\n",
                "(This error occurred for '", 
                getFromSupplyControl_RR(sourceField), "')") |>
           errWrap())
    
  }
  
  
  # The final checks are specific to the SPI DAT file 
  if (datType == "SPI") {
    
    # Get the bounds of the water year being modeled
    wyBounds <- getModeledWY(endDate)
    
    
    # The predicted values in 'datFile' must extend to the end of the water year
    if (max(datFile$DATE) < wyBounds[2]) {
      
      stop(paste0("Incomplete SPI DAT File - End of Water Year\n\n",
                  "The DAT file that contains predictions for the current water ",
                  "year is missing data. It does not extend to the end of the ",
                  "water year (\"", wyBounds[2], "\"). Please adjust ",
                  "this file.\n\n",
                  "(This error occurred for '", 
                  getFromSupplyControl_RR(sourceField), "')") |>
             errWrap())
      
      # Similarly, if 'endDate' is an earlier date than the start of 'datFile', 
      # there should be no gap between then
    } else if (endDate + 1 < min(datFile$DATE)) {
      
      stop(paste0("SPI DAT File and 'endDate' - Data Gap Issue\n\n",
                  "Because the meteorological dataset ends at ", endDate,
                  ", there will be a data gap issue with this DAT file. Its ",
                  "earliest date is ", min(datFile$DATE), ", which means ",
                  "that not all dates will have data when running PRMS with ",
                  "these files. Please adjust either the DAT file or 'endDate' ",
                  "in the control script.\n\n",
                  "(This error occurred for '", 
                  getFromSupplyControl_RR(sourceField), "')") |>
             errWrap())
      
    }
    
  }
  
  
  # If there are no issues, return 'datFile'
  # (It now has a "DATE" column)
  return(datFile |> arrange(DATE))
  
}



predictCurrentWY <- function (mergedDAT, startDate, endDate, prmsCols,
                              dirPath, srpPath, pathMainDAT) {
  
  # Based on 'endDate', apply different methods to select predictions 
  # to append to 'mergedDAT'
  
  
  # For October - February, use the SPI prediction method
  if (month(endDate) < 3 || month(endDate) > 9) {
    
    # Append SPI data to 'mergedDAT'
    finalDAT <- spiPrediction(mergedDAT, startDate, endDate, prmsCols)
    
    
    # Update the metadata file next
    updateMetadata_DAT(dirPath, "SPI", pathMainDAT, getModeledWY(endDate)[2],
                       pathSPI = pathSPI)
    
    
    # If 'endDate' is within March - September, the most similar WY will be used
  } else {
    
    # But first confirm that 'endDate' is not the end of the current water year
    # If that is the case, no predictions are needed
    if (endDate == getModeledWY(endDate)[2]) {
      
      # No additional data is needed for the water year
      finalDAT <- mergedDAT
      
      
      # Update the metadata file after that
      updateMetadata_DAT(dirPath, "Not Required", pathMainDAT, 
                         getModeledWY(endDate)[2])
      
    } else {
      
      # Otherwise, perform all operations for the similar water year procedure
      # in a separate function 
      finalDAT <- similarWYPrediction(mergedDAT, startDate, endDate,
                                      dirPath, srpPath, pathMainDAT)
      
      # The metadata will be updated in that function too
      
    }
    
  }
  
  
  # Make sure the "Runoff" columns all contain "1" for every row
  # (The meteorological dataset does not have these columns, and that causes
  #  "NA" entries to appear)
  finalDAT <- finalDAT |>
    mutate(across(starts_with("RUNOFF"), ~replace_na(., 1)))
  
  
  # Perform a few checks on 'finalDAT'
  validateInputDAT(finalDAT, sourceField = NULL, prmsCols,
                   startDate, endDate, datType = "Final")
  
  
  # Then, return 'finalDAT'
  return(finalDAT)
  
}



spiPrediction <- function (mergedDAT, startDate, endDate, prmsCols) {
  
  # Use the Standard Precipitation Index (SPI) to predict precipitation
  # and temperature for the rest of the water year
  
  
  # At this point in time, insufficient precipitation data is available
  # Predictions using the SPI will be appended to the DAT file
  pathSPI <- getFromSupplyControl_RR("PRMS_DAT_SPI_FILE")
  
  
  spiDAT <- pathSPI |>
    getFile("\t")
  
  
  # Validate the DAT file before continuing
  spiDAT <- validateInputDAT(spiDAT, "PRMS_DAT_SPI_FILE", prmsCols, 
                             startDate, endDate, datType = "SPI")
  
  
  # Filter 'spiDAT' to dates after the last date in 'mergedDAT'
  # Then, append it to 'mergedDAT'
  finalDAT <- mergedDAT |>
    bind_rows(spiDAT |> filter(DATE > max(mergedDAT$DATE)))
  
  
  return(finalDAT)
  
}



getModeledWY <- function (endDate) {
  
  # Based on the value of 'endDate', identify the water year being modeled
  # Then, return a vector of dates containing the bounds of that water year
  
  
  # (1) Determining the starting bound:
  
  #     If 'endDate' is between January and September (inclusive), the water year
  #     matches the calendar year in 'endDate'
  
  #     If that is true, then the water year starts on October 1st of the 
  #     preceding calendar year
  
  #     (e.g., if it's 2026-03-09, we are modeling WY2026, which began on 
  #      2025-10-01)
  
  #     If 'endDate' is in the October - December range, the water year is the
  #     calendar year plus one
  
  #     In addition, the start of the water year is October 1st of the same year
  #     as 'endDate'
  
  #     (e.g., if it's 2024-12-12, we are modeling WY2025, which began on 
  #      2024-10-01)
  
  
  # (2) Determining the ending bound:
  
  #     If 'endDate' is between January and September (inclusive), the water year
  #     matches the calendar year in 'endDate'
  
  #     If that is true, then the water year ends on September 30th of the 
  #     current calendar year
  
  #     (e.g., if it's 2026-03-09, we are modeling WY2026, which ends on 
  #      2026-09-30)
  
  #     If 'endDate' is in the October - December range, the water year is the
  #     calendar year plus one
  
  #     In addition, the end of the water year is September 30th of the next year
  #     after the year in 'endDate'
  
  #     (e.g., if it's 2024-12-12, we are modeling WY2025, which ends on 
  #      2025-09-30)
  
  
  # Get the start and end dates of the water year
  # Then, return them as a vector of dates
  return(c(start = if_else(month(endDate) < 10,
                           paste0(year(endDate) - 1, "-10-01"),
                           paste0(year(endDate), "-10-01")),
           end = if_else(month(endDate) < 10,
                         paste0(year(endDate), "-09-30"),
                         paste0(year(endDate) + 1, "-09-30"))) |>
           as.Date(format = "%Y-%m-%d"))
  
}



updateMetadata_DAT <- function (dirPath, predictionMethod, pathMainDAT, 
                                modelEndDate, pathSPI = NA_character_, 
                                similarWY = NA_real_, linModel = NULL) {
  
  # Update "metadata.csv" in the model run hydrology folder
  
  # Add information about the water year prediction method and the 
  # component DAT files
  
  
  # Get the expected path of the metadata CSV file
  # (Its existence was already confirmed at the start of the script using  
  #  the function `checkForHydroFolder`)
  metaPath <- paste0(dirPath, "/metadata.csv") |>
    normalizePath()
  
  
  # Read in the file
  metaDF <- getFile(metaPath, fileType = "CSV")
  
  
  # Add the water prediction method into 'metaDF'
  metaDF <- metaDF |>
    mutate(MAIN_DAT_FILE = pathMainDAT,
           SPI_DAT_FILE = pathSPI,
           WY_PREDICTION_METHOD = predictionMethod,
           MOST_SIMILAR_WY = similarWY,
           REGRESSION_MODEL_SLOPE = if_else(is.null(linModel),
                                            NA_real_, linModel$m),
           REGRESSION_MODEL_INTERCEPT = if_else(is.null(linModel),
                                                NA_real_, linModel$b),
           MODEL_END_DATE = modelEndDate)
  
  
  # Write 'metaDF' back to "metadata.csv" 
  metaDF |> 
    writeOutput(metaPath, quietly = TRUE)
  
  
  # Return nothing
  return(invisible(NULL))
  
}



similarWYPrediction <- function (mergedDAT, startDate, endDate, 
                                 dirPath, srpPath, pathMainDAT) {
  
  # Use 'mergedDAT' as-is without any predictions appended and 
  # prepare for a model run
  
  # Run PRMS to get the "rr_budget.out2" file
  
  # Then, apply a regression model to identify the most similar water year
  # The hard-coded model coefficients are here:
  linModel <- list("FEB" = list(m = 1.06123659152113, b = 3.84494429543525),
                   "MAR" = list(m = 1.08706793979007, b = 0.833608488137486),
                   "APR" = list(m = 1.02259029456379, b = 0.627031577682994),
                   "MAY" = list(m = 1.00332226548437, b = 0.263608157053314),
                   "JUN" = list(m = 0.998668183546254, b = 0.148860933464808),
                   "JUL" = list(m = 0.998945430679489, b = 0.12814054299168),
                   "AUG" = list(m = 0.998332437810631, b = 0.118465777984958))
  
  
  # The model to use depends on the current month in 'endDate'
  # The chosen model will cover October to the previous month
  linModel <- linModel[[toupper(month.abb[month(endDate) - 1])]]
  
  
  # Perform the model run first
  
  # Prepare a DAT file that extends only up to 'endDate'
  outputDAT(mergedDAT, startDate, endDate, dirPath, srpPath, 
            predictWY = FALSE, quietly = TRUE)
  
  
  # Run PRMS next
  similarWY_runPRMS()
  
  
  # The "rr_budget.out2" file from this process is needed for the analysis
  outDF <- similarWY_processOut2(srpPath, dirPath)
  
  
  # Find the most similar water year for the current water year after that
  similarWY <- similarWY_findWY(endDate, outDF, dirPath, 
                                month(endDate) - 1, linModel)
  
  
  # Create a final DAT tibble after that using the similar water year
  finalDAT <- similarWY_appendDAT(mergedDAT, endDate, similarWY)
  
  
  # Finally, update the metadata file
  updateMetadata_DAT(dirPath, "WY", pathMainDAT, getModeledWY(endDate)[2], 
                     similarWY = similarWY, linModel = linModel)
  
  
  # Return 'finalDAT'
  return(finalDAT)
  
}



outputDAT <- function (mergedDAT, startDate, endDate, dirPath, srpPath, 
                       predictWY, quietly = FALSE) {
  
  # Write 'mergedDAT' to two folders:
  #  (1) In the hydrology directory, store the file under "PRMS > Input"
  #  (2) In the copied PRMS model files, 
  #      under "PRMS > input > climate_scenarios" 
  
  
  # The final filename of 'mergedDAT' will contain 'startDate', 'endDate', and
  # the name of the user running this script
  datName <- paste0("DAT_PRMS_", Sys.info()[["user"]], "_", startDate, 
                    "_", endDate, ".dat")
  
  
  # 'datName' will appear in the hydrology folder only
  # In "RR_PRMS", a generic name will be used instead
  genericName <- "RR_PRMS_Input.dat"
  
  
  # Create a finalized version of 'mergedDAT':
  #  (1) Remove the "DATE" column
  #  (2) Round every numeric value to one decimal place (at most)
  #  (3) Convert every column to character (needed for the next step)
  finalDAT <- mergedDAT |>
    select(-DATE) |>
    mutate(across(where(is.numeric), ~ round(., 1))) |>
    mutate(across(everything(), as.character))
  
  
  # Add a header to the DAT file as well
  # It mainly describes the number of columns 
  headerDAT <- tibble(YEAR = c("Originally generated by J.A.Engott",
                               paste0("precip ", names(finalDAT) |> 
                                        str_subset("PRECIP") |> length()),
                               paste0("tmax ", names(finalDAT) |> 
                                        str_subset("TMAX") |> length()),
                               paste0("tmin ", names(finalDAT) |> 
                                        str_subset("TMIN") |> length()),
                               paste0("runoff ", names(finalDAT) |> 
                                        str_subset("RUNOFF") |> length()),
                               rep("#", 73) |> paste0(collapse = "")))
  
  
  finalDAT <- bind_rows(headerDAT,
                        finalDAT) |>
    mutate(across(everything(), ~replace_na(., "")))
  
  
  # Write 'finalDAT' to the hydrology folder first
  finalDAT |>
    writeOutput(paste0(dirPath, "/PRMS/Input/", datName) |> 
                  normalizePath(mustWork = FALSE),
                writeFunction = "write_tsv", quietly = quietly,
                col_names = FALSE)
  
  
  # Write 'finalDAT' to the PRMS model folder next
  # The name will be fixed as "RR_PRMS_Input.dat" 
  # for ease of modeling automation
  finalDAT |>
    writeOutput(paste0(srpPath, 
                       "/PRMS/input/climate_scenarios/", genericName) |> 
                  normalizePath(mustWork = FALSE),
                writeFunction = "write_tsv", quietly = quietly,
                col_names = FALSE)
  
  
  # Update the PRMS control file next
  # (Its presence was already confirmed at the beginning of the script in 
  #  `checkForPRMS`)
  updateControlFilePRMS(srpPath, genericName, endDate, predictWY)
  
  
  # Finally, update the PRMS batch file
  updateBatchFilePRMS(srpPath)
  
  
  # Return nothing
  return(invisible(NULL))
  
}



updateControlFilePRMS <- function (srpPath, datName, endDate, predictWY) {
  
  # Update the fields in the "prms_rr" control file
  # This customizes the PRMS model run
  
  
  # First, read in the file
  controlPath <- paste0(srpPath, "/windows/prms_rr.control") |>
    normalizePath()
  
  
  prmsControl <- controlPath |>
    getFile(fileType = "OTHER")
  
  
  # 'prmsControl' is a vector of strings, with each element corresponding to a 
  # line of the control file
  # The parameters in these lines will be customized in preparation 
  # for the model run
  
  
  # The first parameter to update is the end date for the model run
  
  # This value will be based on 'predictWY'
  # If 'predictWY' is FALSE, use 'endDate'
  # Otherwise, use the end of the current water year
  if (predictWY) {
    
    modelEnd <- getModeledWY(endDate)[2]
    
  } else {
    
    modelEnd <- endDate
    
  }
  
  
  # Locate "end_time" in the control file
  targetLoc <- grep("^end_time$", prmsControl)[1]
  
  
  # Three lines after "end_time", the next three lines are the components of 
  # the end date for the model run
  prmsControl[targetLoc + 3] <- modelEnd |> year()
  prmsControl[targetLoc + 4] <- modelEnd |> month() |> sprintf(fmt = "%.2d")
  prmsControl[targetLoc + 5] <- modelEnd |> day() |> sprintf(fmt = "%.2d")
  
  
  # The next parameter to update is the name of the input DAT file
  # This will be a fixed name in all cases for ease of automation
  
  # This information is stored under the "data_file" parameter
  targetLoc <- grep("^data_file$", prmsControl)[1]
  
  
  # Three lines after "data_file", the DAT filename is specified
  prmsControl[targetLoc + 3] <- paste0("..\\PRMS\\input\\climate_scenarios\\",
                                       datName)
  
  
  # The final parameter to change is the name of the output file
  # This is stored under "nsubOutBaseFileName"
  targetLoc <- grep("^nsubOutBaseFileName$", prmsControl)[1]
  
  
  # Three lines after "nsubOutBaseFileName", the final output name is specified
  # To make the automated process easier, the name will always 
  # be "RR_PRMS_Output_"
  prmsControl[targetLoc + 3] <- "..\\PRMS\\output\\RR_PRMS_Output_"
  
  
  # Write 'prmsControl' back to a file (overwriting the previous version)
  writeOutput(prmsControl, controlPath, "write_lines", quietly = TRUE)
  
  
  # Return nothing
  return(invisible(NULL))
  
}



updateBatchFilePRMS <- function (srpPath) {
  
  # Update the "run.bat" file that initiates PRMS
  
  
  # This file contains two commands:
  # cd [RR_PRMS "WINDOW" FOLDER]
  # [PATH TO GSFLOW.EXE] [PATH TO CONTROL FILE]
  
  
  batchCommands <- c(paste0("cd ", srpPath, "\\windows"),
                     "..\\bin\\gsflow.exe prms_rr.control")
  
  # The first command changes the working directory to the "windows" sub-folder
  # of "RR_PRMS"
  # The second command then executes gsflow.exe using "prms_rr.control" (which
  # is also located in the "windows" sub-folder)
  
  
  # Write these commands to "run.bat"
  batchCommands |>
    writeOutput(paste0(srpPath, "/windows/run.bat") |> 
                  normalizePath(mustWork = FALSE),
                "write_lines", quietly = TRUE)
  
  
  # Return nothing
  return(invisible(NULL))
  
}



similarWY_runPRMS <- function () {
  
  # To find the most similar water year, a PRMS run is required
  
  
  # Start by notifying the user about this run
  message(paste0("To find the most similar water year, a preliminary PRMS ",
                 "model run will be performed."))
  
  
  # This script will run the "Run_PRMS" script next
  prmsScript <- "Scripts/RRS_009_Run_PRMS.R"
  
  
  # But before doing so, edit the next script to disable the 
  # environment-clearing commands
  scriptCode <- getFile(prmsScript, fileType = "OTHER")
  
  
  # Locate the two lines of code that clear the environment
  clearIndices <- grep("^[#]*\\s*remove\\(list = ls\\(\\)\\)\\s*$", scriptCode)
  
  
  # Add a "#" to the beginning of those lines to comment them out
  scriptCode[clearIndices] <- scriptCode[clearIndices] |>
    str_replace("^(.+)$", "#\\1")
  
  
  # Save the updates to the script
  writeOutput(scriptCode, prmsScript, "write_lines", quietly = TRUE)
  
  
  # Next, run the PRMS execution script
  source(prmsScript)
  
  
  # Once that script is complete, revert the environment-clearing code to its
  # original state (i.e., uncomment those lines)
  scriptCode[clearIndices] <- scriptCode[clearIndices] |>
    str_remove("^[#]+")
  
  
  # Save the reverted version
  writeOutput(scriptCode, prmsScript, "write_lines", quietly = TRUE)
  
  
  # Return nothing
  return(invisible(NULL))
  
}



similarWY_processOut2 <- function (srpPath, dirPath) {
  
  # PRMS was successfully run for the watershed
  
  # The next step is to process its "rr_budget.out2" file
  
  
  # Before starting that, copy the "rr_budget.out2" file from the PRMS "output"
  # folder and save it into the hydrology folder
  out2Path <- paste0(srpPath, "/PRMS/output/rr_budget.out2") |>
    normalizePath(mustWork = TRUE)
  
  
  newOutPath <- paste0(dirPath, "/PRMS/Input/SimilarWY_NoPredict_rr_budget.out2")
  
  
  copyRes <- file.copy(from = out2Path, to = newOutPath, 
                       overwrite = TRUE)
  
  
  # Verify that the file copied successfully
  # If not, output an error message
  if (!copyRes || !file.exists(newOutPath)) {
    
    stop(paste0("Could Not Copy Out2 File\n\n",
                "The script attempted to copy the \"rr_budget.out2\" ",
                "file (\"", out2Path, "\") to the new output directory.\n\n",
                "However, the processed failed for an unknown reason ",
                "(possibly a permission issue). Please investigate.\n\n",
                "The intended new file was: \"", newOutPath, "\"") |>
           errWrap())
    
  }
  
  
  # Read in the .out2 file next
  outDF <- read_out2(out2Path)
  
  
  # Confirm that "Year", "mo", "day", and "ppt (in)" are columns in 'outDF'
  # (The names of the elements in this vector are the planned column names)
  # (The elements themselves are the current expected column names)
  expectedCols <- c("YEAR" = "Year",
                    "MONTH" = "mo",
                    "DAY" = "day",
                    "PRECIP" = "ppt (in)")
  
  
  if (anyFalse(expectedCols %in% names(outDF))) {
    
    missingColumns <- which(!(expectedCols %in% names(outDF)))
    
    
    stop(paste0("Missing Columns in Out2 File\n\n",
                "Several of the expected columns in PRMS's \"rr_budget.out2\" ",
                "output file could not be found (",
                expectedCols[missingColumns] |> vec2QuotedStr(),
                "). Please investigate the file and update the script if ",
                "needed.\n\n",
                "(This error occurred for \"", out2Path, "\")") |>
           errWrap())
    
  }
  
  
  # Rename these columns in 'outDF' and return only those columns
  return(outDF |>
           select(all_of(expectedCols)))
  
}



similarWY_findWY <- function (endDate, outDF, dirPath, endMonth, linModel) {
  
  # In WY2024, SDA staff developed a calibrated and validated linear regression
  # model that linked Oct - Feb Precipitation to Total WY Precipitation
  
  # In WY2026, similar models were developed for Oct - Mar, Oct - Apr, Oct - May,
  # Oct - Jun, Oct - July, and Oct - Aug using data for WY2025
  
  # These models will now be applied here to find the most similar water year
  # for the current water year
  
  # Given the partial precipitation, the total precipitation for the water year
  # will be estimated
  
  # Then, this predicted total will be compared to the total precipitation
  # in previous water years
  
  # The "most similar water year" will have a total precipitation closest to 
  # the current water year's predicted total
  
  
  # First, make sure that 'endMonth' is a valid value
  # It should correspond to a month between February and August
  if (!(endMonth %in% 2:8)) {
    
    stop(paste0("Script Error - Invalid 'endMonth'\n\n",
                "The \"Similar Water Year\" method uses data from October to ",
                "a month between February and August (inclusive) to predict ",
                "the total precipitation for the current water year. As a ",
                "result, the input \"endMonth\" should have a value between 2 ",
                "and 8 (inclusive). However, \"", endMonth, "\" was provided to ",
                "`similarWY_findWY` instead. Please revise the script.") |>
           errWrap())
    
  }
  
  
  # Get the current water year 
  currentWY <- getModeledWY(endDate)[2] |> year()
  
  
  # Adjust the formatting of 'outDF'
  # Add water year and date columns
  outDF <- outDF |>
    mutate(WY = if_else(MONTH < 10, YEAR, YEAR + 1),
           DATE = paste0(YEAR, "-", MONTH, "-", DAY) |>
             as.Date(format = "%Y-%m-%d")) |>
    filter(!is.na(PRECIP)) |>
    arrange(DATE)
  
  
  # Calculate the partial precipitation for the current water year
  # It will be Oct - Feb/Mar/Apr/May/Jun/Jul/Aug
  partialPrecip <- outDF |>
    filter(WY == currentWY) |>
    filter(MONTH > 9 | MONTH <= endMonth) |>
    select(PRECIP) |>
    sum()
  
  
  # Apply the linear regression model to get the predicted total this year
  predictedPrecip <- linModel$m * partialPrecip + linModel$b
  
  
  # Before finding the most similar water year in 'outDF', some additional
  # adjustments are necessary first
  
  # Only keep water years in 'outDF' that have a complete set of data
  # (Ignore the current water year too)
  
  # To determine which water years are missing data, two approaches will be used
  
  # First, a count of days for every water year will be established
  # Any year with less than 365 days of data is incomplete
  # These water years should be removed from 'outDF'
  countDF <- outDF |>
    group_by(WY) |>
    summarize(COUNT = n()) |>
    filter(COUNT < 365)
  
  
  # Water years with incomplete data will be removed from 'outDF'
  # (At this step, the current water year will be excluded too)
  outDF <- outDF |>
    filter(!(WY %in% countDF$WY | WY == currentWY))
  
  
  # The second method to determine which water years are missing data will rely
  # on a separate tibble of expected dates
  # (This extra check is needed because some years should have 365 days 
  #  and others should have 366. It could be cleaner to just verify that water  
  #  years have 365 days by default and require 366 if YEAR %% 4 == 0, but 
  #  this method can also weed out instances where a date is missing and another 
  #  date is duplicated in the same water year--it is unlikely to happen though)
  dateDF <- tibble(DATE = seq(from = min(outDF$DATE), 
                              to = max(outDF$DATE), 
                              by = "days")) |>
    mutate(WY = if_else(month(DATE) < 10, year(DATE), year(DATE) + 1))
  
  
  # Figure out which dates are missing in 'outDF' from 'dateDF'
  missingDates <- which(!(dateDF$DATE %in% outDF$DATE))
  
  
  # If missing dates are found, remove their water years from 'outDF'
  if (length(missingDates) > 0) {
    
    # Identify the water years that correspond to the missing dates
    incompleteWYs <- dateDF$WY[missingDates] |> unique()
    
    
    # Remove those water years from 'outDF'
    outDF <- outDF |>
      filter(!(WY %in% incompleteWYs))
    
  }
  
  
  # Now that all incomplete water years have been excluded, calculate
  # the partial precipitation and total water year precipitation for
  # every water year in 'outDF'
  precipDF <- outDF |>
    group_by(WY) |>
    summarize(!! paste0("OCT_TO_", toupper(month.abb[endMonth]), 
                        "_PARTIAL_PRECIP") := 
                sum(PRECIP[MONTH > 9 | MONTH <= endMonth]),
              TOTAL_WY_PRECIP = sum(PRECIP), 
              .groups = "drop")
  
  
  # Using 'predictedPrecip', calculate the absolute difference between 
  # every value of "TOTAL_WY_PRECIP" and this predicted total
  precipDF <- precipDF |>
    mutate(ERROR = abs(TOTAL_WY_PRECIP - predictedPrecip))
  
  
  # Identify which water year has the smallest absolute difference
  # (If multiple water years have the same minimum error, the most recent water
  #  year will be chosen. Its data quality will be higher and more accurate.)
  similarWY <- precipDF$WY[which.min(precipDF$ERROR)] |> max()
  
  
  # Before returning 'similarWY', this information will be output into a 
  # spreadsheet in the hydrology model input/output folder
  
  # Append additional information to 'precipDF':
  #  (1): The current water year's information will be appended at the end
  #       (It has a partial precipitation value like the other columns, 
  #        but its total water year is a prediction, so that will be listed
  #        in a separate column)
  #  (2): Identify the years that have the minimum error
  #  (3): Identify the year labeled as "most similar"
  
  # After that, rearrange the columns in 'precipDF' and make sure it is sorted
  precipDF <- precipDF |>
    bind_rows(tibble(WY = currentWY,
                     !! paste0("OCT_TO_", toupper(month.abb[endMonth]), 
                               "_PARTIAL_PRECIP") := partialPrecip,
                     PREDICTED_TOTAL_WY_PRECIP = predictedPrecip)) |>
    mutate(MINIMUM_ABS_DIFFERENCE_ERROR = !is.na(ERROR) &
             ERROR == min(ERROR, na.rm = TRUE),
           MOST_SIMILAR_WY = (WY == similarWY)) |>
    select(WY, paste0("OCT_TO_", toupper(month.abb[endMonth]), 
                      "_PARTIAL_PRECIP"), TOTAL_WY_PRECIP,
           PREDICTED_TOTAL_WY_PRECIP, ERROR, MINIMUM_ABS_DIFFERENCE_ERROR,
           MOST_SIMILAR_WY) |>
    arrange(WY)
  
  
  # Write 'precipDF' as a CSV file to 'dirPath' next
  precipDF |>
    writeOutput(paste0(dirPath, "/PRMS/Input/SimilarWY_Analysis.csv") |>
                  normalizePath(mustWork = FALSE),
                "write_csv")
  
  
  # Finally, return 'similarWY'
  return(similarWY)
  
}



similarWY_appendDAT <- function (mergedDAT, endDate, similarWY) {
  
  # Copy the data in 'mergedDAT' from a previous water year and 
  # use it as predictions for the rest of the current water year
  
  
  # Get the current water year's bounds
  currentWY <- getModeledWY(endDate)
  
  
  # Extract data from 'mergedDAT' for the water year identified in 'similarWY'
  wyDAT <- mergedDAT |>
    filter(DATE >= paste0(similarWY - 1, "-10-01") &
             DATE <= paste0(similarWY, "-09-30"))
  
  
  # Adjust the "YEAR" and "DATE" columns to be for the current water year
  wyDAT <- wyDAT |>
    mutate(YEAR = if_else(MONTH < 10, year(currentWY[2]), year(currentWY[1]))) |>
    mutate(DATE = paste0(YEAR, "-", MONTH, "-", DAY) |> 
             as.Date(format = "%Y-%m-%d"))
  
  
  # Filter 'wyDAT' to after 'endDate'
  wyDAT <- wyDAT |>
    filter(DATE > endDate)
  
  
  # Append 'wyDAT' to 'mergedDAT' and return it
  return(mergedDAT |>
           bind_rows(wyDAT))
  
}



#### Script Execution ####

mainProcedure()


# Clean up
remove(list = ls())
