# After PRMS and SRP have been run successfully, combine the outputs into 
# a single CSV that describes the raw flows available in each sub-basin
# of the Russian River watershed


# This script has several required input files:
#  (1) The "_sub_inq.csv" file generated by PRMS
#  (2) The six "_inflow_#.gag" files generated by SRP
#  (3) A CSV file containing reduction factors to apply to the GAG files' values


# These files will be combined into a single output file:
#  (1) "Raw_Flows.csv"

#### Setup ####

# Clear the environment
base::remove(list = ls())


# Import packages
source("Scripts/HLP_000_Load_Packages.R")


# Import shared functions
source("Scripts/HLP_001_Shared_Functions_Supply.R")
source("Scripts/HLP_003_RR_Workflow_Validation_Functions.R")


#### Functions ####

mainProcedure <- function () {
  
  cat("\n\n")
  cat("Starting 'RRW_016_Generate_Raw_Flows.R'!\n")
  
  
  # Import the start and end date
  source("Scripts/HLP_002_Validate_and_Import_Data_Scraping_Bounds.R")
  
  
  # Locate and validate the required PRMS and SRP model files
  cat("[1/4]\tChecking input files...\n")
  
  
  # Check that the model hydrology folder exists
  dirPath <- validateHydroFolder(startDate, endDate)
  
  
  # From the PRMS model files, the "sub_inq.csv" output is required
  # Locate that file and confirm its existence
  inqPath <- paste0(dirPath, "/PRMS/Output") |>
    list.files(pattern = paste0("_", startDate, "_", 
                                endDate, "_sub_inq\\.csv"), 
               full.names = TRUE) |>
    sort() |> tail(1) |>
    normalizePath(mustWork = FALSE) |>
    checkForPreviousOutput()
  
  
  # Locate the six SRP files next and confirm their existence
  gagPaths <- paste0(dirPath, "/SRP/Output/SRP_inflow_", 1:6, ".gag") |>
    normalizePath(mustWork = FALSE) |> 
    checkForPreviousOutput()
  
  
  # Get the path to the CSV containing SRP reduction factors 
  # These proportions will be applied to the values in 'gagPaths' later
  reductPath <- getFromControl_RR("GAG_FLOW_REDUCTION_FACTORS_CSV")
  
  
  # After that, read in the input files and validate them
  
  # Start with the PRMS output file
  inqDF <- getDelim(inqPath, ",", trim_ws = TRUE) |>
    validateInqCSV(inqPath, dirPath)
  
  
  # Read in the six SRP GAG files next
  gagList <- vector(mode = "list", length = length(gagPaths))
  
  
  # Iteratively read in and validate the GAG files
  for (i in 1:length(gagList)) {
    
    gagList[[i]] <- read_gag(gagPaths[i]) |>
      validateGag(gagPaths[i], dirPath)
    
  }
  
  
  # Finally, read in and validate the reduction factors
  reductionDF <- getFile(reductPath) |>
    validateReductionFactors(reductPath, length(gagList))
  
  
  cat("\tDone!\n\n")
  
  
  # The next step is to process the files and generate supply flows
  # for each sub-basin
  cat("[2/4]\tProcessing data...\n")
  
  
  # Process 'inqDF' and turn it into monthly flows (with volume units of AF)
  inqDF <- inqDF |>
    processInqCSV()
  
  
  # Do the same for the GAG files (though their procedure is more involved)
  gagDF <- gagList |>
    processGag(reductionDF)
  
  
  cat("\tDone!\n\n")
  
  
  # Combine 'inqDF' and 'gagDF' together to produce the final supply CSV file
  cat("[3/4]\tGenerating raw hydrologic flows...\n")
  
  
  # Generate 'flowDF' and validate its values
  flowDF <- mergeAndValidateFlows(inqDF, gagDF)
  
  
  cat("\tDone!\n\n")
  
  
  # Finally, write outputs to the model hydrology folder (and update metadata)
  cat("[4/4]\tSaving outputs...\n")
  
  
  # Store 'flowDF' in the "DWRAT" "Input" folder
  flowName <- paste0(dirPath, "/DWRAT/Input/",
                     "Raw_Flows_", Sys.info()[["user"]],
                     "_", Sys.Date(), ".csv") |>
    normalizePath(mustWork = FALSE)
  
  
  flowDF |>
    writeOutput(flowName, "write_csv")
  
  
  # Archive 'reductionDF' in the model hydrology folder too
  reductionName <- paste0(dirPath, "/DWRAT/Input/SRP_Reduction_Factors.csv") |>
    normalizePath(mustWork = FALSE)
  
  
  reductionDF |>
    writeOutput(reductionName,
                "write_csv", quietly = TRUE)
  
  
  # Update the metadata CSV file to contain the names of the "Raw_Flows" and
  # "Reduction_Factors" CSV files
  updateMetadataCSV(dirPath,
                    list("RAW_FLOWS_CSV" = flowName |>
                           str_remove("^.+[/\\\\]"),
                         "SRP_GAG_REDUCTION_FACTORS" = reductionName |>
                           str_remove("^.+[/\\\\]")))
  
  
  cat("\tDone!\n\n")
  
  
  # Output a completion message
  cat(col_green("\n'RRW_016_Generate_Raw_Flows.R' is complete!\n\n"))
  
  
  # Return nothing
  return(invisible(NULL))
  
}



validateInqCSV <- function (inqDF, inqPath, dirPath, nsub = 22) {
  
  # Check the "sub_inq" output of PRMS
  
  # It should contain simulated hydrological flows for the first 22 sub-basins 
  
  
  # First, confirm that 'inqDF' contains a "Date" column and 22 sub-basin columns
  if (length(names(inqDF)) != (1 + nsub)) {
    
    paste0("Unexpected Number of Columns in sub_inq CSV\n\n",
           "The PRMS output file (\"", inqPath, "\") should contain a \"Date\" ",
           "column and ", nsub, " additional column",
           if_else(nsub > 1, "s ", " "), "(one for each modeled sub-basin ",
           "in the Russian River watershed). Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Check for the exact column names too
  if (anyFalse(c("Date" %in% names(inqDF), 1:nsub %in% names(inqDF)))) {
    
    paste0("Unexpected Columns in sub_inq CSV\n\n",
           "The PRMS output file (\"", inqPath, "\") should contain a \"Date\" ",
           "column and ", nsub, " additional column",
           if_else(nsub > 1, "s ", " "), "(one for each modeled sub-basin ",
           "in the Russian River watershed). Each sub-basin column header ",
           "should be a number that corresponds to a modeled sub-basin",
           if_else(nsub > 1, paste0(" (\"1\" to \"", nsub, "\")"), ""), ". ",
           "Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that the sub-basin flow columns are numeric
  if (anyFalse(map_lgl(inqDF[names(inqDF) != "Date"], is.numeric))) {
    
    # Identify the non-numeric columns (ignoring "Date")
    nonNumCols <- which(!map_lgl(inqDF, is.numeric)) |>
      base::setdiff(which(names(inqDF) == "Date"))
    
    
    # Use 'nonNumCols' in the error message
    paste0("PRMS sub_inq File - Column Type Issue\n\n",
           "The PRMS output file (\"", inqPath, "\") should contain a \"Date\" ",
           "column and ", nsub, " additional column",
           if_else(nsub > 1, "s ", " "), "(one for each modeled sub-basin ",
           "in the Russian River watershed). Each sub-basin column should be ",
           "numeric. However, ", length(nonNumCols), " column",
           if_else(length(nonNumCols) > 1, "s ", " "), " (", 
           vec2QuotedStr(names(inqDF)[nonNumCols]), ") ",
           if_else(length(nonNumCols) > 1, "are", "is"), " a different type. ",
           "Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that 'inqDF' contains data from the start of PRMS to the end of 
  # the modeled water year
  
  # "metadata.csv" contains this information
  # Read in the required columns (while making sure that the fields are dates)
  metaDF <- dirPath |>
    getColsFromMetadata(c("PRMS_MODEL_START_DATE", "PRMS_MODEL_END_DATE")) |>
    mutate(PRMS_MODEL_START_DATE = as.Date(PRMS_MODEL_START_DATE, 
                                           format = "%m/%d/%Y"),
           PRMS_MODEL_END_DATE = as.Date(PRMS_MODEL_END_DATE, 
                                         format = "%m/%d/%Y"))
  
  
  # Confirm that every date between "PRMS_MODEL_START_DATE" and
  # "PRMS_MODEL_END_DATE" is present in 'inqDF'
  dateSeq <- seq(from = metaDF$PRMS_MODEL_START_DATE[1],
                 to = metaDF$PRMS_MODEL_END_DATE[1],
                 by = "days")
  
  
  # This vector will contain the indices of dates that are missing
  # (It will be empty if no data is missing)
  missingDates <- which(!(dateSeq %in% inqDF$Date))
  
  
  if (length(missingDates) > 0) {
    
    paste0("PRMS sub_inq File - Missing Data Issue\n\n",
           "The PRMS output file (\"", inqPath, "\") should contain daily ",
           "flow values (in cfs). However, ", length(missingDates),
           if_else(length(missingDates) > 1, " dates are ", " date is "),
           "missing data (", vec2QuotedStr(dateSeq[missingDates]), "). ",
           "Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # As a final check, ensure no values are "NA" in 'inqDF'
  if (anyNA(inqDF)) {
    
    paste0("PRMS sub_inq File - Missing Data Issue\n\n",
           "The PRMS output file (\"", inqPath, "\") should contain daily ",
           "flow values (in cfs). However, missing elements were detected in ",
           "the file. Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  
  # Return 'inqDF' after that
  return(inqDF)
  
}



getColsFromMetadata <- function (dirPath, colNames) {
  
  # Check "metadata.csv" for specific fields
  # Return a data frame containing only those columns
  
  
  # First, read in the metadata CSV file
  metaDF <- paste0(dirPath, "/metadata.csv") |>
    normalizePath(mustWork = FALSE) |>
    getFile(",")
  
  
  # Confirm that the desired columns are in 'metaDF'
  if (anyFalse(colNames %in% names(metaDF))) {
    
    missingNames <- which(!(colNames %in% names(metaDF)))
    
    
    paste0("Metadata CSV File - Column",
           if_else(length(missingNames) > 1, "s", ""), 
           " Not Found\n\n",
           "The metadata file (located within \"", dirPath, "\") ",
           "is missing ", length(missingNames), " column",
           if_else(length(missingNames) > 1, "s", ""), " (", 
           vec2QuotedStr(colNames[missingNames]), ").\n\n", 
           "Please investigate and revise the scripts to address this ",
           "issue.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # If there are no issues, return only the specified columns from 'metaDF'
  return(metaDF |>
           select(all_of(colNames)))
  
}



validateGag <- function (gagDF, gagPath, dirPath) {
  
  # Check the GAG output file of SRP
  
  # It should contain simulated hydrological flows
  
  
  # First, confirm that 'gagDF' contains "Time" and "Flow" columns
  requiredCols <- c("Time", "Flow")
  
  
  # Check for the exact column names too
  if (anyFalse(requiredCols%in% names(gagDF))) {
    
    missingColumns <- which(!(requiredCols %in% names(gagDF)))
    
    paste0("Missing Columns in SRP GAG File\n\n",
           "The SRP output file (\"", gagPath, "\") should have several ",
           "specific columns (", vec2QuotedStr(requiredCols), "). However, ",
           "this is not the case (missing ", 
           vec2QuotedStr(requiredCols[missingColumns]), 
           "). Please investigate the file (", vec2QuotedStr(gagPath), 
           ") and `read_gag`.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that the "Time" and "Flow" columns are numeric
  if (anyFalse(map_lgl(gagDF[requiredCols], is.numeric))) {
    
    # Identify the non-numeric columns
    nonNumCols <- which(!map_lgl(gagDF[requiredCols], is.numeric))
    
    
    # Use 'nonNumCols' in the error message
    paste0("SRP GAG File - Column Type Issue\n\n",
           "The SRP output file (\"", gagPath, "\") should have several ",
           "specific columns (", vec2QuotedStr(requiredCols), "). These ",
           "columns should all have numeric values. However, that is not the ",
           "case for all columns (", 
           vec2QuotedStr(requiredCols[nonNumCols]), 
           "). Please investigate the file (", vec2QuotedStr(gagPath), 
           ") and `read_gag`.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that 'gagDF' contains data from the start of the SRP run to the end 
  # of the modeled water year
  
  # "metadata.csv" contains this information
  # Read in the required columns (while making sure that the fields are dates)
  metaDF <- dirPath |>
    getColsFromMetadata(c("SRP_MODEL_START_DATE", "SRP_MODEL_END_DATE")) |>
    mutate(SRP_MODEL_START_DATE = as.Date(SRP_MODEL_START_DATE, 
                                           format = "%m/%d/%Y"),
           SRP_MODEL_END_DATE = as.Date(SRP_MODEL_END_DATE, 
                                         format = "%m/%d/%Y"))
  
  
  # Confirm that every date between "SRP_MODEL_START_DATE" and
  # "SRP_MODEL_END_DATE" is present in 'inqDF'
  dateSeq <- seq(from = metaDF$SRP_MODEL_START_DATE[1],
                 to = metaDF$SRP_MODEL_END_DATE[1],
                 by = "days")
  
  
  # The main issue is that 'gagDF' does not have a date column
  # "Time" is just a count from the start date
  
  # Verify then that the length of 'dateSeq' equals the number of
  # rows in 'gagDF'
  if (length(dateSeq) != nrow(gagDF)) {
    
    paste0("SRP Gag File - Missing Data Issue\n\n",
           "The SRP GAG files should contain daily flow values (in cfs). ",
           "However, this file contains ", nrow(gagDF), " records when ",
           length(dateSeq), " are expected. Please investigate the file (",
           vec2QuotedStr(gagPath), ").") |>
      errWrap() |>
      stop()
    
  }
  
  
  # If there are no missing dates, add 'dateSeq' to 'gagDF'
  # (This will be easier to work with than "Time")
  gagDF <- gagDF |>
    arrange(Time) |>
    mutate(DATE = dateSeq)
  
  
  # As a final check, ensure no values are "NA" in 'gagDF'
  if (anyNA(gagDF)) {
    
    paste0("SRP Gag File - Missing Data Issue\n\n",
           "The SRP GAG files should contain daily flow values (in cfs). ",
           "However, this file contains missing elements where values are ",
           "expected. Please investigate the file (",
           vec2QuotedStr(gagPath), ") and `read_gag`.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Return 'gagDF' after that
  return(gagDF)
  
}



validateReductionFactors <- function (reductionDF, reductPath, numGag) {
  
  # This CSV file should contain decimal proportions to apply to 
  # the flow values in each of the GAG files
  
  # Check that all required columns are present
  # Sensible values should be input as well
  
  
  # First, confirm that 'reductionDF' contains a "Month" column 
  # It should also have a separate numeric column for each GAG file
  if (length(names(reductionDF)) != (1 + numGag)) {
    
    paste0("Unexpected Number of Columns in SRP Reduction Factors CSV\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column and ", numGag, " additional column",
           if_else(numGag > 1, "s ", " "), "(one for each GAG file output by ",
           "SRP). Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Check for the exact column names too
  if (anyFalse(c("Month" %in% names(reductionDF), 
                 1:numGag %in% names(reductionDF)))) {
    
    paste0("Unexpected Columns in SRP Reduction Factors CSV\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column and ", numGag, " additional column",
           if_else(numGag > 1, "s ", " "), "(one for each GAG file output by ",
           "SRP). Each GAG file's column header should be a number that ",
           "corresponds to that file's index number ",
           if_else(numGag > 1, paste0(" (\"1\" to \"", numGag, "\")"), ""), 
           ". Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that all columns are numeric
  if (anyFalse(map_lgl(reductionDF, is.numeric))) {
    
    # Identify the non-numeric columns
    nonNumCols <- which(!map_lgl(reductionDF, is.numeric))
    
    
    # Use 'nonNumCols' in the error message
    paste0("SRP Reduction Factors CSV File - Column Type Issue\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column and ", numGag, " additional column",
           if_else(numGag > 1, "s ", " "), "(one for each GAG file output by ",
           "SRP). Every column should be numeric. However, ", length(nonNumCols),
           " column", if_else(length(nonNumCols) > 1, "s ", " "), " (", 
           vec2QuotedStr(names(reductionDF)[nonNumCols]), ") ",
           if_else(length(nonNumCols) > 1, "are", "is"), " a different type. ",
           "Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that "Month" has a value for all months of the year
  if (anyFalse(1:12 %in% reductionDF$Month) || nrow(reductionDF) != 12) {
    
    paste0("SRP Reduction Factors CSV File - Incomplete Data Issue\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column with one row per month. However, this ",
           "is not the case. Please investigate the file.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Check for "NA" values after that
  if (anyNA(reductionDF)) {
    
    paste0("SRP Reduction Factors CSV File - Missing Data Issue\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain a \"Month\" column and ", numGag, "columns that correspond ",
           "to each SRP GAG file. There should be one row per month, and a ",
           "reduction factor for each GAG file. However, one or more missing ",
           "elements were detected in the file. Please investigate it.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # The reduction factors should primarily be less than 1
  # Output a warning if any reduction factor is greater than 1
  if (max(reductionDF[names(reductionDF) != "Month"]) > 1) {
    
    paste0("Warning! Unusual Factor Detected!\n\n",
           "The Reduction Factors CSV file (\"", reductPath, "\") should ",
           "contain factors that reduce the flow values in GAG files (e.g., ",
           "0.90 for a 10% reduction). However, at least one proportion is ",
           "greater than one. Was that intentional?") |>
      errWrap() |>
      message()
    
  }
  
  
  # Return 'reductionDF' after that
  return(reductionDF)
  
}



processInqCSV <- function (inqDF) {
  
  # The PRMS sub_inq file contains daily flows in cubic feet per second (cfs)
  
  # This data will be wrapped up into monthly flows 
  # The new units will be acre-feet per month (AF/month)
  
  
  # First, convert "cfs" into acre-feet per day:
  
  #  (*) There are 43,559.9 ft^3 in 1 AF
  #  (*) There are 60 * 60 * 24 seconds in 1 day
  
  # ft^3/s * 60 s/min * 60 min/hr * 24 hr/day * 1/43559.9 AF/ft^3
  inqDF <- inqDF |>
    mutate(across(matches("[0-9]"), ~ . * 60 * 60 * 24 / 43559.9))
  
  
  # After that, sum up the AF/day values by year and month
  inqDF <- inqDF |>
    mutate(YEAR = year(Date),
           MONTH = month(Date)) |>
    group_by(YEAR, MONTH) |>
    summarize(across(matches("[0-9]"), sum), .groups = "drop")
  
  
  # Return 'inqDF' afterwards
  return(inqDF)
  
}



processGag <- function (gagList, reductionDF) {
  
  # The six SRP GAG files contain daily flows in cubic feet per second (cfs)*
  
  # This data will be consolidated into monthly flows for six sub-basins in the
  # Russian River watershed
  # The new units will be acre-feet per month (AF/month)
  
  # * = Although the units are stated to be cfs, they are wrapped up into daily 
  # values already, meaning that ft^3/day is the actual starting point for 
  # unit conversions
  
  
  # From each GAG file, extract the "DATE" and "Flow" columns
  # Rename "Flow" and then combine these GAG files together
  for (i in 1:length(gagList)) {
    
    tempDF <- gagList[[i]] |>
      select(DATE, Flow) |>
      rename(!! paste0("GAG_", i) := Flow)
    
    
    # Consolidate 'tempDF' from each of the GAG files
    if (i == 1) {
      
      gagDF <- tempDF
      
    } else {
      
      gagDF <- full_join(gagDF, tempDF, by = "DATE", 
                         relationship = "one-to-one")
      
    }
    
  }
  
  
  # Use "DATE" to calculate a "YEAR" and "Month" column 
  # After that, append 'reductionDF' using "Month"
  gagDF <- gagDF |>
    mutate(YEAR = year(DATE), Month = month(DATE)) |>
    left_join(reductionDF, by = "Month", relationship = "many-to-one")
  
  
  # Apply the reduction factors to the daily CFS values
  gagDF[paste0("GAG_", 1:length(gagList))] <- 
    gagDF[paste0("GAG_", 1:length(gagList))] * gagDF[as.character(1:length(gagList))]
  
  
  # Keep only the datetime columns and "GAG" columns before proceeding
  # (Rename "Month" into "MONTH" too)
  gagDF <- gagDF |>
    select(DATE, YEAR, Month, starts_with("GAG_")) |>
    rename(MONTH = Month)
  
  
  # Convert the units from ft^3/day to AF/day next
  # (There are 43,559.9 cubic feet in 1 acre-foot)
  gagDF <- gagDF |>
    mutate(across(starts_with("GAG_"), ~ . / 43559.9))
  
  
  # After that, define the sub-basin flow values using the GAG data
  gagDF <- gagDF |>
    mutate(`23` = GAG_1,
           `24` = GAG_6 - GAG_1 - GAG_5,
           `25` = GAG_5 - GAG_4 - GAG_3,
           `26` = GAG_4 - GAG_2,
           `27` = GAG_2,
           `28` = GAG_3)
  
  
  # Finally, summarize the data by YEAR and MONTH (giving units of AF/month)
  gagDF <- gagDF |>
    group_by(YEAR, MONTH) |>
    summarize(across(matches("^[0-9]"), sum), .groups = "drop")
  
  
  # Return 'gagDF'
  return(gagDF)
  
}



mergeAndValidateFlows <- function (inqDF, gagDF, numBasins = 28) {
  
  # Combine 'inqDF' and 'gagDF' into a sub-basin flows tibble
  
  # All 28 sub-basins of the Russian River watershed should be represented here
  
  
  # Before combining the two variables, confirm that there are no missing values
  if (anyNA(inqDF)) {
    
    paste0("PRMS sub_inq - Missing Data Issue\n\n",
           "Processing the PRMS 'sub_inq' file led to it gaining \"NA\" ",
           "values. The source file was checked earlier, and it was not ",
           "missing any values. Please investigate the script.") |>
      errWrap() |>
      stop()
    
  }
  
  
  if (anyNA(gagDF)) {
    
    paste0("SRP GAG Files - Missing Data Issue\n\n",
           "Processing the SRP 'sub_inq' files led to 'gagDF' gaining \"NA\" ",
           "values. The source files were checked earlier, and they were not ",
           "missing any values. Please investigate the script.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Also, check that both variables contain "YEAR" and "MONTH"
  if (anyFalse(c("YEAR", "MONTH") %in% names(inqDF)) ||
      anyFalse(c("YEAR", "MONTH") %in% names(gagDF))) {
    
    paste0("'inqDF' and 'gagDF' - Missing Column Issue\n\n",
           "This procedure expects 'inqDF' and 'gagDF' to contain both a ",
           "\"YEAR\" and a \"MONTH\" column. However, that is not the case. ",
           "Please investigate the script, and update it accordingly.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Create a "Date" column in both 'inqDF' and 'gagDF'
  # Use "YEAR" and "MONTH", and set the day to be "1"
  inqDF <- inqDF |>
    mutate(Date = paste0(YEAR, "-", MONTH, "-01") |>
             as.Date(format = "%Y-%m-%d")) |>
    select(-c(YEAR, MONTH))
  
  
  gagDF <- gagDF |>
    mutate(Date = paste0(YEAR, "-", MONTH, "-01") |>
             as.Date(format = "%Y-%m-%d")) |>
    select(-c(YEAR, MONTH))
  
  
  
  # Merge 'inqDF' and 'gagDF' using the "Date" column
  flowDF <- inqDF |>
    full_join(gagDF, by = "Date",
              relationship = "one-to-one")
  
  
  # Sub-basins 1 through 28 should be represented among them (with no repeats)
  if (anyFalse(1:numBasins %in% names(flowDF))) {
    
    paste0("Missing Sub-Basin Column(s)\n\n",
           "The combination of the PRMS \"sub_inq\" file and the SRP GAG ",
           "files should result in a data frame that contains data for ",
           numBasins, " sub-basins. Each sub-basin should have its own ",
           "column (named \"1\" through \"", numBasins, "\"). However, ",
           "that is not the case. Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Filter the dataset to start from the more recent start date
  # between 'inqDF' and 'gagDF'
  laterStart <- c(min(inqDF$Date), min(gagDF$Date)) |>
    max()
  
  
  flowDF <- flowDF |>
    filter(Date >= laterStart)
  
  
  # Verify that 'flowDF' does not contain any missing values
  if (anyNA(flowDF)) {
    
    paste0("Missing Data in Sub-Basin Flows\n\n",
           "The combination of the PRMS \"sub_inq\" file and the SRP GAG ",
           "files should result in a data frame that contains monthly flow ",
           "data for ", numBasins, " sub-basins from ", 
           min(flowDF$Date) |> format("%B %Y"), " to ", 
           max(flowDF$Date) |> format("%B %Y"), ". However, one or more ",
           "entries are \"NA\". Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # After that, confirm that no months are missing from 'flowDF'
  monthVec <- seq(from = min(flowDF$Date), 
                  to = max(flowDF$Date), 
                  by = "months")
  
  
  missingMonths <- monthVec[!(monthVec %in% flowDF$Date)]
  
  
  if (length(missingMonths)) {
    
    paste0("Missing Data in Sub-Basin Flows\n\n",
           "The combination of the PRMS \"sub_inq\" file and the SRP GAG ",
           "files should result in a data frame that contains monthly flow ",
           "data for ", numBasins, " sub-basins from ", 
           min(flowDF$Date) |> format("%B %Y"), " to ", 
           max(flowDF$Date) |> format("%B %Y"), ". However, ", 
           length(missingMonths), " month", 
           if_else(length(missingMonths) > 1, "s are", " is"), " missing (",
           missingMonths |> format("%B %Y") |> vec2QuotedStr(), "). ",
           "Please investigate.") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Output a warning if negative flows are detected in 'flowDF'
  if (map_lgl(flowDF, ~ any(. < 0)) |> any()) {
    
    # Get the specific sub-basins with negative flows
    negIndices <- flowDF |>
      map_lgl(~ !is.Date(.) & any(. < 0)) |>
      which()
    
    
    paste0("\nNegative flows detected in data for Subbasin",
           if_else(length(negIndices) > 1, "s", ""), " ",
           vec2QuotedStr(names(flowDF)[negIndices]), "!") |>
      errWrap() |>
      message()
    
    cat("\n")
    
  }
  
  
  # Finally, adjust the formatting of 'flowDF' and return it
  return(flowDF |>
           select(Date, all_of(as.character(1:numBasins))) |>
           arrange(Date))
  
}



#### Script Execution ####

mainProcedure()


# Clean up
base::remove(list = ls())

