# Import Library Dependencies
import os, sys
from pathlib import Path

# Import important variable information from a temporary Python script
# (generated by LSPC_005a_Download_and_Stage_Climate_Data.R)
import temp

# This variable contains the path to this file too
tempPath = os.path.join(Path(__file__).parent, Path('temp.py'))


# Add workspace root to Python path to enable imports
workspace_root = Path(__file__).parent.parent
sys.path.insert(0, str(workspace_root))
print(f"Added to sys.path: {workspace_root}")

from src import WeatherDataEtl

print(f'System Paths: {sys.path}\n\n')
print(f'cwd: {os.getcwd()}')


# Next, use the values provided in the temporary Python script


# Path to master control file
master_control_file = temp.master_control_file


# Earth Data credentials (optional)
if (temp.username != ''):

    # If the username variable is not an empty string in the temporary script,
    # update the environment to store Earth Data credentials
    os.environ['EARTHDATA_USERNAME'] = temp.username
    os.environ['EARTHDATA_PASSWORD'] = temp.password


# After that, delete the temporary Python script
os.remove(tempPath)


# Prepare the object for gathering climate data
app = WeatherDataEtl()


# Setup project directories
projects = app.builder.build_projects(master_control_file=master_control_file)
print(f'Found {len(projects)} project(s)')


for project in projects:
    app.builder.build_storage_respository(project)


# Begin fetching climate data


# PRISM
for project in projects:
    app.run.fetch.prism(project)


# CIMIS
for project in projects:
    app.run.fetch.cimis(project)


# NLDAS
for project in projects:
    app.run.fetch.nldas(project)


# NOAA
for project in projects:
    app.run.fetch.gage.noaa(project)


# CDEC
for project in projects:
    app.run.fetch.gage.cdec(project)


# LCD
for project in projects:
    app.run.fetch.gage.lcd(project)


# RAWS
for project in projects:
    app.run.fetch.gage.raws(project)


# Process the downloaded data next (i.e., Staging)


# NLDAS (must be first)
for project in projects:
    app.run.stage.nldas(project)


# PRISM
for project in projects:
    app.run.stage.prism(project)


# CIMIS
for project in projects:
    app.run.stage.cimis(project)


# Gage data (NOAA, CDEC, LCD, and/or RAWS)
for project in projects:
    app.run.qc_gage_data(project)


# Manual review spreadsheets will now be generated 
# The next step is for users to review flagged data for errors
