# When running models, there are often input and output files that should be preserved

# These functions help with managing file archives


#' @title Copy a File to a Model Archive Sub-Folder
#' 
#' @description
#' Given the path to a file, this function copies that file to an archive directory. 
#' The same filename will be used, but the path will become 
#' `outputDirectory/model/subDir/filename`. 
#' 
#' @details
#' `outputDirectory` contains the path to the archive folder. Within this folder,
#' there should be a folder with the same name as `model`. Inside the model folder,
#' there should be folders with names like "Input" and "Output". `subDir` should contain
#' the name of the planned destination folder under the model folder. 
#' 
#' These three parameters help construct the planned destination path for the 
#' input file. Using [extract_filename()], the final piece is pulled from 
#' `inputPath`. After that, `copyFile` (a function still contained within 
#' the "Shared_Scripts" folder) is called to perform the file copy procedure.
#' 
#' Please note that the function is vectorized, so `inputPath` can contain one or
#' more filepaths. The destination folder will be the same in all cases. 
#' 
#' @usage copy_file_to_archive(inputPath, outputDirectory, 
#'                      model = "PRMS", subDir = "Input") 
#' 
#' @param inputPath A [character] vector containing one or more file paths.
#' 
#' @param outputDirectory A [character] string that contains the path to the 
#' archive folder.
#' 
#' @param model A [character] string for the name of the model folder 
#' (exactly as it appears in the archive folder). 
#' 
#' @param subDir A [character] string that contains the name of the sub-folder 
#' under `model` that will be the archive destination of the file. 
#' 
#' @returns NULL (invisibly)
#' 
#' @export
#' 
#' @examples
#' \dontrun{
#' # Example archive directory path
#' archiveDir <- "C:/Users/person/Archive"
#' 
#' # Example file
#' myFilePath <- "W2_Russian_River/Input/my_file.csv"
#' 
#' 
#' # Save the file to the "Output" folder under "PRMS" in 'archiveDir'
#' copy_file_to_archive(myFilePath, archiveDir, "PRMS", "Output")
#' 
#' # The copy's path will be "C:/Users/person/Archive/PRMS/Output/my_file.csv"
#' 
#' 
#' # Altneratively, save the file to the "Example" folder under "SRP" in 'archiveDir'
#' copy_file_to_archive(myFilePath, archiveDir, "SRP", "Example")
#' 
#' # The copy's path will be "C:/Users/person/Archive/SRP/Example/my_file.csv"
#' }
copy_file_to_archive <- function (inputPath, outputDirectory, model = "PRMS",
                                  subDir = "Input") {
  
  # Given a path to a file, copy it to a sub-folder of 'outputDirectory' 
  # with a similar filename
  
  
  # If 'inputPath' is NULL, end the function without doing anything
  if (is.null(inputPath)) {
    return(invisible(NULL))
  }
  
  
  # Otherwise, start by setting the output path
  
  # Modify 'inputPath' into a location within the model's sub-folder
  # in 'outputDirectory'
  outputPath <- paste0(outputDirectory, "/", model, "/", subDir, "/",
                       extract_filename(inputPath))
  
  
  # Copy the file
  copyFile(inputPath, outputPath, quietly = TRUE)
  
  
  # Return nothing
  return(invisible(NULL))
  
}



#' @title Get a Model Run's Associated Archive Folder
#' 
#' @description
#' Given the start date and end date bounds of the model run procedure as well 
#' as the location of archive text files, this function locates this run's 
#' specific file and retrieves the archive path from it. 
#' 
#' 
#' @details
#' Model procedure involves generating a text file 
#' ...
#' 
#' @usage ...
#' 
#' @param ... ...
#' 
#' @returns ...
#' 
#' @export
#' 
#' @examples
#' \dontrun{
#' # Example archive directory path
#' ...
#' }
get_archive_path <- function (startDate, endDate, dir, nameStr = "Archive_Location_") {
  
  # Verify that previous scripts were run successfully and that a hydrology archive 
  # folder was created to store metadata and model files
  
  # This function can also return the directory path
  
  
  # Get the text file that contains the path to the hydrology folder
  folderFilePath <- paste0(dir, "/", nameStr, 
                           startDate, "_", endDate, ".txt") |>
    normalizePath(mustWork = FALSE)
  
  
  # Output an error message if the file was not found
  if (!file.exists(folderFilePath)) {
    
    paste0("Model Run Folder Not Found\n\n",
           "A folder to store metadata and model inputs/outputs should ",
           "have been generated by an earlier script in this process. ",
           "An accompanying output was a text file that identifies its ",
           "location. However, it was not found. ",
           "Please run the previous scripts before running this one.\n\n",
           "The expected file was \"", folderFilePath, "\"") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Read in the text file to get the path to the actual folder
  dirPath <- getFile(folderFilePath, fileType = "OTHER")[1]
  
  
  # Make sure the username matches (if "C:/Users/..." is detected)
  if (grepl("^C:[/\\\\]Users[/\\\\].+", dirPath)) {
    
    # Substitute the username to ensure that it matches the current user
    # This ensures that different users can try to access the same path
    # in case it's shared (e.g., on SharePoint)
    dirPath <- dirPath |>
      stringr::str_replace("^C:[/\\\\]Users[/\\\\].+?[/\\\\]",
                  paste0("C:/Users/", Sys.info()[["user"]], "/")) |>
      normalizePath(mustWork = FALSE)
    
    # The two regular expressions look complicated, but here's what they mean:
    
    #   (*) The path starts with "C:"
    #   (*) Followed by either a single "/" or a single "\"
    #   (*) Followed by "Users"
    #   (*) Followed by either a single "/" or a single "\"
    
    # The second regex has two additional components:
    #   (*) Followed by one or more characters (lazy evaluation)
    #   (*) Followed by either a single "/" or a single "\"
    
    # There are two things worth noting here:
    #
    #   (1) The regular expression for a forward slash is just "/", but for 
    #       a backslash it's "\\\\"
    #
    #       This is because "\" is a special character for escaping other
    #       special characters (including itself)
    # 
    #       We have to escape the backslash (using another backslash "\\") 
    #       to disable its special properties, but then both of the backslashes 
    #       must be escaped too for this (to signify that they are being escaped,
    #       and that they are not escaping another character). This ends up 
    #       leading to "\\\\".
    #
    #   (2) Lazy evaluation of "+"
    #       Since "+" means one or more, the pattern could match with the bare
    #       minimum, or go as far as possible
    #       The former is a "lazy" approach, while the latter is a "greedy" one
    #
    #       If I place a "?" right after the "+", it chooses the lazy approach
    #  
    #       This is necessary because ".+/" could go all the way to the last 
    #       folder "/" in the path. 
    #
    #       Consider this path for example: "C:/Users/me/one/two/three"
    #
    #       If I use "^C:[/\\\\]Users[/\\\\].+[/\\\\]" as the regex instead,
    #       it will match with "C:/Users/me/one/two/" because the greedy matching
    #       style is the default
    #
    #       By adding a "?" after the "+" ("^C:[/\\\\]Users[/\\\\].+?[/\\\\]"),
    #       the pattern will instead match with just "C:/Users/me/"
    
  }
  
  
  # Make sure that folder exists 
  if (!dir.exists(dirPath)) {
    
    paste0("Model Run Folder Not Found\n\n",
           "A folder to store metadata and model inputs/outputs should ",
           "have been generated by an earlier script in this process. ",
           "However, it was not found. ",
           "Please run the previous scripts before running this one.\n\n",
           "The expected directory was \"", dirPath, "\"") |>
      errWrap() |>
      stop()
    
  }
  
  
  # Confirm that the metadata CSV file exists too
  metaPath <- paste0(dirPath, "/metadata.csv") |>
    normalizePath(mustWork = FALSE)
  
  
  if (!file.exists(metaPath)) {
    
    stop(paste0("Missing Metadata File\n\n",
                "When the hydrology folder was setup, a metadata CSV file ", 
                "should have been generated. However, it was not found. ",
                "Please investigate.\n\n",
                "(This error occurred for \"", metaPath, "\")") |>
           errWrap())
    
  }
  
  
  # If there are no issues, return 'dirPath'
  return(dirPath)
  
}
